const catalogoProductos = [
  { id: 'LIFE3-01', name: "AGUA LIFE 3 LT x 6 unidades - CON GAS", price: 3590, category: "AGUA", image: "catalogo/LIFE3.webp" },
  { id: 'LIFE3-02', name: "AGUA LIFE 3 LT x 6 unidades - SIN GAS", price: 3590, category: "AGUA", image: "catalogo/LIFE3.webp" },
  { id: 'MASC-01', name: "AGUA MAS 600ML X12 UNID - UVA SIN GAS", price: 10516, category: "AGUA", image: "catalogo/MASC.webp" },
  { id: 'MASC-02', name: "AGUA MAS 600ML X12 UNID - MANZANASIN GAS", price: 10516, category: "AGUA", image: "catalogo/MASC.webp" },
  { id: 'MASC-03', name: "AGUA MAS 600ML X12 UNID - PERA SIN GAS", price: 10516, category: "AGUA", image: "catalogo/MASC.webp" },
  { id: 'MASC-04', name: "AGUA MAS 600ML X12 UNID - GRANADA SIN GAS", price: 10516, category: "AGUA", image: "catalogo/MASC.webp" },
  { id: 'MASC-05', name: "AGUA MAS 600ML X12 UNID - MANGO MARACUYA SIN GAS", price: 10516, category: "AGUA", image: "catalogo/MASC.webp" },
  { id: 'MASC-06', name: "AGUA MAS 600ML X12 UNID - CITRUS CON GAS", price: 10516, category: "AGUA", image: "catalogo/MASC.webp" },
  { id: 'MASC-07', name: "AGUA MAS 600ML X12 UNID - FRUTOS DEL BOSUQE CON GAS", price: 10516, category: "AGUA", image: "catalogo/MASC.webp" },
  { id: 'MASC-08', name: "AGUA MAS 600ML X12 UNID - LIMONADA FRAMBUESA", price: 10516, category: "AGUA", image: "catalogo/MASC.webp" },
  { id: 'NEST15', name: "AGUA MINERAL NESTLE PURE LIFE 1.5L", price: 1500, category: "AGUA", image: "catalogo/NEST15.webp" },
  { id: 'ALOEO-01', name: "ALOE VERA 500ML X CAJA - ORIGINAL", price: 17952, category: "BEBIDAS", image: "catalogo/ALOEO.webp" },
  { id: 'ALOEO-02', name: "ALOE VERA 500ML X CAJA - PIÑA", price: 17952, category: "BEBIDAS", image: "catalogo/ALOEO.webp" },
  { id: 'ALOEO-03', name: "ALOE VERA 500ML X CAJA - FRUTILLA", price: 17952, category: "BEBIDAS", image: "catalogo/ALOEO.webp" },
  { id: 'ALOEO-04', name: "ALOE VERA 500ML X CAJA - MANGO", price: 17952, category: "BEBIDAS", image: "catalogo/ALOEO.webp" },
  { id: 'ALOEO-05', name: "ALOE VERA 500ML X CAJA - DURAZNO", price: 17952, category: "BEBIDAS", image: "catalogo/ALOEO.webp" },
  { id: 'ALOEO-06', name: "ALOE VERA 500ML X CAJA - GRANADA", price: 17952, category: "BEBIDAS", image: "catalogo/ALOEO.webp" },
  { id: 'ALOEO-07', name: "ALOE VERA 500ML X CAJA - COCO", price: 17952, category: "BEBIDAS", image: "catalogo/ALOEO.webp" },
  { id: 'AND400-01', name: "ANDINA DEL VALLE 400ML x 6 unidades - DURAZNO", price: 5040, category: "BEBIDAS", image: "catalogo/AND400.webp" },
  { id: 'AND400-02', name: "ANDINA DEL VALLE 400ML x 6 unidades - NARANJA", price: 5040, category: "BEBIDAS", image: "catalogo/AND400.webp" },
  { id: 'AND400-03', name: "ANDINA DEL VALLE 400ML x 6 unidades - PIÑA", price: 5040, category: "BEBIDAS", image: "catalogo/AND400.webp" },
  { id: 'AND400-04', name: "ANDINA DEL VALLE 400ML x 6 unidades - TUTIFRUTILLA", price: 5040, category: "BEBIDAS", image: "catalogo/AND400.webp" },
  { id: 'ANDVA15-01', name: "ANDINA DEL VALLE DESECHABLE x 6 unidades - DURAZNO", price: 6540, category: "BEBIDAS", image: "catalogo/ANDVA15.webp" },
  { id: 'ANDVA15-02', name: "ANDINA DEL VALLE DESECHABLE x 6 unidades - TUTIFRUTILLA", price: 6540, category: "BEBIDAS", image: "catalogo/ANDVA15.webp" },
  { id: 'ANDVA15-03', name: "ANDINA DEL VALLE DESECHABLE x 6 unidades - NARANJA", price: 6540, category: "BEBIDAS", image: "catalogo/ANDVA15.webp" },
  { id: 'ANDVA15-04', name: "ANDINA DEL VALLE DESECHABLE x 6 unidades - PIÑA", price: 6540, category: "BEBIDAS", image: "catalogo/ANDVA15.webp" },
  { id: 'ANDVA15-05', name: "ANDINA DEL VALLE DESECHABLE x 6 unidades - DAMASCO", price: 6540, category: "BEBIDAS", image: "catalogo/ANDVA15.webp" },
  { id: 'ANDMANLATA', name: "ANDINA DEL VALLE MANZANA LATA 340ML X6", price: 4200, category: "BEBIDAS", image: "catalogo/ANDMANLATA.webp" },
  { id: 'ANDMULTI', name: "ANDINA DEL VALLE MULTI-FRUTILLA 1.5L", price: 1800, category: "BEBIDAS", image: "catalogo/ANDMULTI.webp" },
  { id: 'ANDPACK', name: "ANDINA DEL VALLE PACK SURTIDO", price: 4500, category: "BEBIDAS", image: "catalogo/ANDPACK.webp" },
  { id: 'ARROZ', name: "ARROZ MANGA 10 UNID", price: 6950, category: "BEBIDAS", image: "catalogo/ARROZ.webp" },
  { id: 'BAV470', name: "BAVARIA 470 ML X24 UNID", price: 12240, category: "CERVEZA", image: "catalogo/BAV470.webp" },
  { id: 'BEN3-01', name: "BENEDICTINO 3LT x 6 unidades - CON GAS", price: 6900, category: "AGUA", image: "catalogo/BEN3.webp" },
  { id: 'BEN3-02', name: "BENEDICTINO 3LT x 6 unidades - SIN GAS", price: 6900, category: "AGUA", image: "catalogo/BEN3.webp" },
  { id: 'BEN5-01', name: "BENEDICTINO 500ML x 12 unidades - CON GAS", price: 4680, category: "AGUA", image: "catalogo/BEN5.webp" },
  { id: 'BEN5-02', name: "BENEDICTINO 500ML x 12 unidades - SIN GAS", price: 4680, category: "AGUA", image: "catalogo/BEN5.webp" },
  { id: 'BOMB200-01', name: "BOMBILLIN 200CC X24 - DURAZNO", price: 6480, category: "BEBIDAS", image: "catalogo/BOMB200.webp" },
  { id: 'BOMB200-02', name: "BOMBILLIN 200CC X24 - PIÑA", price: 6480, category: "BEBIDAS", image: "catalogo/BOMB200.webp" },
  { id: 'BOMB200-03', name: "BOMBILLIN 200CC X24 - NARANJA", price: 6480, category: "BEBIDAS", image: "catalogo/BOMB200.webp" },
  { id: 'BOMB200-04', name: "BOMBILLIN 200CC X24 - MULTIFRUTILLA", price: 6480, category: "BEBIDAS", image: "catalogo/BOMB200.webp" },
  { id: 'BOMB200-05', name: "BOMBILLIN 200CC X24 - MANZANA", price: 6480, category: "BEBIDAS", image: "catalogo/BOMB200.webp" },
  { id: 'PROD004', name: "Bebida Coca Cola Original 2.5L", price: 1890, category: "LICORES", image: "logo.jpg.jpeg" },
  { id: 'PROD005', name: "Bebida Energética Red Bull 250cc", price: 1690, category: "ENERGÉTICAS", image: "logo.jpg.jpeg" },
  { id: 'CATUNSG16-01', name: "CACHANTUN 1.6 LT DESECHABLE x 6 unidades - CON GAS", price: 5520, category: "AGUA", image: "catalogo/CATUNSG16.webp" },
  { id: 'CATUNSG16-02', name: "CACHANTUN 1.6 LT DESECHABLE x 6 unidades - SIN GAS", price: 5520, category: "AGUA", image: "catalogo/CATUNSG16.webp" },
  { id: 'CATUNSG16-03', name: "CACHANTUN 1.6 LT DESECHABLE x 6 unidades - STRONG GAS", price: 5520, category: "AGUA", image: "catalogo/CATUNSG16.webp" },
  { id: 'CATUNSG16-04', name: "CACHANTUN 1.6 LT DESECHABLE x 6 unidades - LIGTH GAS", price: 5520, category: "AGUA", image: "catalogo/CATUNSG16.webp" },
  { id: 'CATUNSG25-01', name: "CACHANTUN 2.5LT DESECHABLE x 6 unidades - CON GAS", price: 6540, category: "AGUA", image: "catalogo/CATUNSG25.webp" },
  { id: 'CATUNSG25-02', name: "CACHANTUN 2.5LT DESECHABLE x 6 unidades - SIN GAS", price: 6540, category: "AGUA", image: "catalogo/CATUNSG25.webp" },
  { id: 'CATUNSG5-01', name: "CACHANTUN 500ML x 12 unidades - CON GAS", price: 4000, category: "AGUA", image: "catalogo/CATUNSG5.webp" },
  { id: 'CATUNSG5-02', name: "CACHANTUN 500ML x 12 unidades - SIN GAS", price: 4000, category: "AGUA", image: "catalogo/CATUNSG5.webp" },
  { id: 'CATUNSG5-03', name: "CACHANTUN 500ML x 12 unidades - STRONG GAS", price: 4000, category: "AGUA", image: "catalogo/CATUNSG5.webp" },
  { id: 'CATUNSG5-04', name: "CACHANTUN 500ML x 12 unidades - LIGTH GAS", price: 4000, category: "AGUA", image: "catalogo/CATUNSG5.webp" },
  { id: 'MASP-01', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - UVA SIN GAS", price: 7521, category: "AGUA", image: "catalogo/MASP.webp" },
  { id: 'MASP-02', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - MANZANASIN GAS", price: 7521, category: "AGUA", image: "catalogo/MASP.webp" },
  { id: 'MASP-03', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - PERA SIN GAS", price: 7521, category: "AGUA", image: "catalogo/MASP.webp" },
  { id: 'MASP-04', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - GRANADA SIN GAS", price: 7521, category: "AGUA", image: "catalogo/MASP.webp" },
  { id: 'MASP-05', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - MANGO MARACUYA SIN GAS", price: 7521, category: "AGUA", image: "catalogo/MASP.webp" },
  { id: 'MASP-06', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - CITRUS CON GAS", price: 7521, category: "AGUA", image: "catalogo/MASP.webp" },
  { id: 'MASP-07', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - FRUTOS DEL BOSUQE CON GAS", price: 7521, category: "AGUA", image: "catalogo/MASP.webp" },
  { id: 'MASP-08', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - LIMONADA FRAMBUESA", price: 7521, category: "AGUA", image: "catalogo/MASP.webp" },
  { id: 'KFE-01', name: "CAFE HELADO NESCAFE X 6 UNID. - LATE", price: 9300, category: "BEBIDAS", image: "catalogo/KFE.webp" },
  { id: 'KFE-02', name: "CAFE HELADO NESCAFE X 6 UNID. - MOCKA", price: 9300, category: "BEBIDAS", image: "catalogo/KFE.webp" },
  { id: 'KFE-03', name: "CAFE HELADO NESCAFE X 6 UNID. - ORIGINAL", price: 9300, category: "BEBIDAS", image: "catalogo/KFE.webp" },
  { id: 'CCU125DES-01', name: "CCU 1.25 DESECHABLE - KEM", price: 5760, category: "BEBIDAS", image: "catalogo/CCU125DES.webp" },
  { id: 'CCU125DES-02', name: "CCU 1.25 DESECHABLE - LIMON", price: 5760, category: "BEBIDAS", image: "catalogo/CCU125DES.webp" },
  { id: 'CCU125DES-03', name: "CCU 1.25 DESECHABLE - BILZ", price: 5760, category: "BEBIDAS", image: "catalogo/CCU125DES.webp" },
  { id: 'CCU125DES-04', name: "CCU 1.25 DESECHABLE - PAP", price: 5760, category: "BEBIDAS", image: "catalogo/CCU125DES.webp" },
  { id: 'CCU125DES-05', name: "CCU 1.25 DESECHABLE - PEPSI", price: 5760, category: "BEBIDAS", image: "catalogo/CCU125DES.webp" },
  { id: 'CCU125DES-06', name: "CCU 1.25 DESECHABLE - PEPSI ZERO", price: 5760, category: "BEBIDAS", image: "catalogo/CCU125DES.webp" },
  { id: 'L125-01', name: "CCU 1.25LT RETORNABLE x 12 unidades - ´PAP", price: 12990, category: "BEBIDAS", image: "catalogo/L125.webp" },
  { id: 'L125-02', name: "CCU 1.25LT RETORNABLE x 12 unidades - BILZ", price: 12990, category: "BEBIDAS", image: "catalogo/L125.webp" },
  { id: 'L125-03', name: "CCU 1.25LT RETORNABLE x 12 unidades - KEM", price: 12990, category: "BEBIDAS", image: "catalogo/L125.webp" },
  { id: 'L125-04', name: "CCU 1.25LT RETORNABLE x 12 unidades - LIMON", price: 12990, category: "BEBIDAS", image: "catalogo/L125.webp" },
  { id: 'L125-05', name: "CCU 1.25LT RETORNABLE x 12 unidades - PEPSI", price: 12990, category: "BEBIDAS", image: "catalogo/L125.webp" },
  { id: 'L125-06', name: "CCU 1.25LT RETORNABLE x 12 unidades - PEPSI ZERO", price: 12990, category: "BEBIDAS", image: "catalogo/L125.webp" },
  { id: 'L25-01', name: "CCU 2.5 LT RETORNABLE x 6 unidades - ´PAP", price: 9498, category: "BEBIDAS", image: "catalogo/L25.webp" },
  { id: 'L25-02', name: "CCU 2.5 LT RETORNABLE x 6 unidades - BILZ", price: 9498, category: "BEBIDAS", image: "catalogo/L25.webp" },
  { id: 'L25-03', name: "CCU 2.5 LT RETORNABLE x 6 unidades - KEM", price: 9498, category: "BEBIDAS", image: "catalogo/L25.webp" },
  { id: 'L25-04', name: "CCU 2.5 LT RETORNABLE x 6 unidades - LIMON", price: 9498, category: "BEBIDAS", image: "catalogo/L25.webp" },
  { id: 'L25-05', name: "CCU 2.5 LT RETORNABLE x 6 unidades - PEPSI", price: 9498, category: "BEBIDAS", image: "catalogo/L25.webp" },
  { id: 'L25-06', name: "CCU 2.5 LT RETORNABLE x 6 unidades - PEPSI ZERO", price: 9498, category: "BEBIDAS", image: "catalogo/L25.webp" },
  { id: 'L25-07', name: "CCU 2.5 LT RETORNABLE x 6 unidades - GINGER", price: 9498, category: "BEBIDAS", image: "catalogo/L25.webp" },
  { id: 'L25-08', name: "CCU 2.5 LT RETORNABLE x 6 unidades - CRUSH", price: 9498, category: "BEBIDAS", image: "catalogo/L25.webp" },
  { id: 'L2-01', name: "CCU 2LT RETORNABLE x 9 unidades - ´PAP", price: 13545, category: "BEBIDAS", image: "catalogo/L2.webp" },
  { id: 'L2-02', name: "CCU 2LT RETORNABLE x 9 unidades - BILZ", price: 13545, category: "BEBIDAS", image: "catalogo/L2.webp" },
  { id: 'L2-03', name: "CCU 2LT RETORNABLE x 9 unidades - KEM", price: 13545, category: "BEBIDAS", image: "catalogo/L2.webp" },
  { id: 'L2-04', name: "CCU 2LT RETORNABLE x 9 unidades - LIMON", price: 13545, category: "BEBIDAS", image: "catalogo/L2.webp" },
  { id: 'L2-05', name: "CCU 2LT RETORNABLE x 9 unidades - PEPSI", price: 13545, category: "BEBIDAS", image: "catalogo/L2.webp" },
  { id: 'L2-06', name: "CCU 2LT RETORNABLE x 9 unidades - PEPSI ZERO", price: 13545, category: "BEBIDAS", image: "catalogo/L2.webp" },
  { id: 'L3-01', name: "CCU 3LT DESECHABLE x 6 unidades - ´PAP", price: 12080, category: "BEBIDAS", image: "catalogo/L3.webp" },
  { id: 'L3-02', name: "CCU 3LT DESECHABLE x 6 unidades - BILZ", price: 12080, category: "BEBIDAS", image: "catalogo/L3.webp" },
  { id: 'L3-03', name: "CCU 3LT DESECHABLE x 6 unidades - KEM", price: 12080, category: "BEBIDAS", image: "catalogo/L3.webp" },
  { id: 'L3-04', name: "CCU 3LT DESECHABLE x 6 unidades - LIMON", price: 12080, category: "BEBIDAS", image: "catalogo/L3.webp" },
  { id: 'L3-05', name: "CCU 3LT DESECHABLE x 6 unidades - PEPSI", price: 12080, category: "BEBIDAS", image: "catalogo/L3.webp" },
  { id: 'L3-06', name: "CCU 3LT DESECHABLE x 6 unidades - PEPSI ZERO", price: 12080, category: "BEBIDAS", image: "catalogo/L3.webp" },
  { id: 'L3-07', name: "CCU 3LT DESECHABLE x 6 unidades - GINGER", price: 12080, category: "BEBIDAS", image: "catalogo/L3.webp" },
  { id: 'L3-08', name: "CCU 3LT DESECHABLE x 6 unidades - CRUSH", price: 12080, category: "BEBIDAS", image: "catalogo/L3.webp" },
  { id: 'L3-09', name: "CCU 3LT DESECHABLE x 6 unidades - SEVEN UP", price: 12080, category: "BEBIDAS", image: "catalogo/L3.webp" },
  { id: 'CCU600-01', name: "CCU 600ML DESECHABLE x 12 unidades - PEPSI", price: 10200, category: "BEBIDAS", image: "catalogo/CCU600.webp" },
  { id: 'CCU600-02', name: "CCU 600ML DESECHABLE x 12 unidades - PESI ZERO", price: 10200, category: "BEBIDAS", image: "catalogo/CCU600.webp" },
  { id: 'CCU600-03', name: "CCU 600ML DESECHABLE x 12 unidades - KEM", price: 10200, category: "BEBIDAS", image: "catalogo/CCU600.webp" },
  { id: 'CCU600-04', name: "CCU 600ML DESECHABLE x 12 unidades - BILZ", price: 10200, category: "BEBIDAS", image: "catalogo/CCU600.webp" },
  { id: 'CCU600-05', name: "CCU 600ML DESECHABLE x 12 unidades - LIMON SODA", price: 10200, category: "BEBIDAS", image: "catalogo/CCU600.webp" },
  { id: 'CCU600-06', name: "CCU 600ML DESECHABLE x 12 unidades - GINGER", price: 10200, category: "BEBIDAS", image: "catalogo/CCU600.webp" },
  { id: 'CCU600-07', name: "CCU 600ML DESECHABLE x 12 unidades - CRUSH", price: 10200, category: "BEBIDAS", image: "catalogo/CCU600.webp" },
  { id: 'CCU600-08', name: "CCU 600ML DESECHABLE x 12 unidades - PAP", price: 10200, category: "BEBIDAS", image: "catalogo/CCU600.webp" },
  { id: 'AND15DES-01', name: "COCA COLA 1.5 LT DESECHABLE x 6 unidades - COCA COLA", price: 9888, category: "BEBIDAS", image: "catalogo/AND15DES.webp" },
  { id: 'AND15DES-02', name: "COCA COLA 1.5 LT DESECHABLE x 6 unidades - COCA COLA ZERO", price: 9888, category: "BEBIDAS", image: "catalogo/AND15DES.webp" },
  { id: 'AND15DES-03', name: "COCA COLA 1.5 LT DESECHABLE x 6 unidades - FANTA", price: 9888, category: "BEBIDAS", image: "catalogo/AND15DES.webp" },
  { id: 'AND15DES-04', name: "COCA COLA 1.5 LT DESECHABLE x 6 unidades - SPRITE", price: 9888, category: "BEBIDAS", image: "catalogo/AND15DES.webp" },
  { id: 'AND15DES-05', name: "COCA COLA 1.5 LT DESECHABLE x 6 unidades - INCA COLA", price: 9888, category: "BEBIDAS", image: "catalogo/AND15DES.webp" },
  { id: 'AND125-01', name: "COCA COLA 125 RETORNABLE x 10 unidades - COCA COLA", price: 10250, category: "BEBIDAS", image: "catalogo/AND125.webp" },
  { id: 'AND125-02', name: "COCA COLA 125 RETORNABLE x 10 unidades - COCA COLA ZERO", price: 10250, category: "BEBIDAS", image: "catalogo/AND125.webp" },
  { id: 'AND125-03', name: "COCA COLA 125 RETORNABLE x 10 unidades - FANTA", price: 10250, category: "BEBIDAS", image: "catalogo/AND125.webp" },
  { id: 'AND125-04', name: "COCA COLA 125 RETORNABLE x 10 unidades - SPRITE", price: 10250, category: "BEBIDAS", image: "catalogo/AND125.webp" },
  { id: 'AND125-05', name: "COCA COLA 125 RETORNABLE x 10 unidades - INCA COLA", price: 10250, category: "BEBIDAS", image: "catalogo/AND125.webp" },
  { id: 'AND2-01', name: "COCA COLA 2LT RETORNABLE x 8 unidades - COCA COLA", price: 11880, category: "BEBIDAS", image: "catalogo/AND2.webp" },
  { id: 'AND2-02', name: "COCA COLA 2LT RETORNABLE x 8 unidades - COCA COLA ZERO", price: 11880, category: "BEBIDAS", image: "catalogo/AND2.webp" },
  { id: 'AND2-03', name: "COCA COLA 2LT RETORNABLE x 8 unidades - FANTA", price: 11880, category: "BEBIDAS", image: "catalogo/AND2.webp" },
  { id: 'AND2-04', name: "COCA COLA 2LT RETORNABLE x 8 unidades - SPRITE", price: 11880, category: "BEBIDAS", image: "catalogo/AND2.webp" },
  { id: 'AND2-05', name: "COCA COLA 2LT RETORNABLE x 8 unidades - INCA COLA", price: 11880, category: "BEBIDAS", image: "catalogo/AND2.webp" },
  { id: 'AND2-06', name: "COCA COLA 2LT RETORNABLE x 8 unidades - SPRITE ZERO", price: 11880, category: "BEBIDAS", image: "catalogo/AND2.webp" },
  { id: 'AND3DES-01', name: "COCA COLA 3LT DESECHABLE x 6 unidades - COCA COLA", price: 14850, category: "BEBIDAS", image: "catalogo/AND3DES.webp" },
  { id: 'AND3DES-02', name: "COCA COLA 3LT DESECHABLE x 6 unidades - COCA COLA ZERO", price: 14850, category: "BEBIDAS", image: "catalogo/AND3DES.webp" },
  { id: 'AND3DES-03', name: "COCA COLA 3LT DESECHABLE x 6 unidades - FANTA", price: 14850, category: "BEBIDAS", image: "catalogo/AND3DES.webp" },
  { id: 'AND3DES-04', name: "COCA COLA 3LT DESECHABLE x 6 unidades - SPRITE", price: 14850, category: "BEBIDAS", image: "catalogo/AND3DES.webp" },
  { id: 'AND3DES-05', name: "COCA COLA 3LT DESECHABLE x 6 unidades - INCA COLA", price: 14850, category: "BEBIDAS", image: "catalogo/AND3DES.webp" },
  { id: 'AND3-01', name: "COCA COLA 3LT RETORNABLE x 6 unidades - COCA COLA", price: 12642, category: "BEBIDAS", image: "catalogo/AND3.webp" },
  { id: 'AND3-02', name: "COCA COLA 3LT RETORNABLE x 6 unidades - COCA COLA ZERO", price: 12642, category: "BEBIDAS", image: "catalogo/AND3.webp" },
  { id: 'AND3-03', name: "COCA COLA 3LT RETORNABLE x 6 unidades - FANTA", price: 12642, category: "BEBIDAS", image: "catalogo/AND3.webp" },
  { id: 'AND3-04', name: "COCA COLA 3LT RETORNABLE x 6 unidades - SPRITE", price: 12642, category: "BEBIDAS", image: "catalogo/AND3.webp" },
  { id: 'AND591-01', name: "COCA COLA 591ML DESECHABLE x 6 unidades - COCA COLA", price: 5760, category: "BEBIDAS", image: "catalogo/AND591.webp" },
  { id: 'AND591-02', name: "COCA COLA 591ML DESECHABLE x 6 unidades - COCA COLA ZERO", price: 5760, category: "BEBIDAS", image: "catalogo/AND591.webp" },
  { id: 'AND591-03', name: "COCA COLA 591ML DESECHABLE x 6 unidades - FANTA", price: 5760, category: "BEBIDAS", image: "catalogo/AND591.webp" },
  { id: 'AND591-04', name: "COCA COLA 591ML DESECHABLE x 6 unidades - SPRITE", price: 5760, category: "BEBIDAS", image: "catalogo/AND591.webp" },
  { id: 'LATAC-01', name: "COCA COLA LATA 350 ML x 6 unidades - COCA COLA", price: 4428, category: "BEBIDAS", image: "catalogo/LATAC.webp" },
  { id: 'LATAC-02', name: "COCA COLA LATA 350 ML x 6 unidades - COCA COLA ZERO", price: 4428, category: "BEBIDAS", image: "catalogo/LATAC.webp" },
  { id: 'LATAC-03', name: "COCA COLA LATA 350 ML x 6 unidades - FANTA", price: 4428, category: "BEBIDAS", image: "catalogo/LATAC.webp" },
  { id: 'LATAC-04', name: "COCA COLA LATA 350 ML x 6 unidades - SPRITE", price: 4428, category: "BEBIDAS", image: "catalogo/LATAC.webp" },
  { id: 'LATAC-05', name: "COCA COLA LATA 350 ML x 6 unidades - INCA COLA", price: 4428, category: "BEBIDAS", image: "catalogo/LATAC.webp" },
  { id: 'ICE275-01', name: "COCTEL CAPEL ICE 275 ML X 24 - SANDIA", price: 19000, category: "LICORES", image: "catalogo/ICE275.webp" },
  { id: 'ICE275-02', name: "COCTEL CAPEL ICE 275 ML X 24 - MOJITO", price: 19000, category: "LICORES", image: "catalogo/ICE275.webp" },
  { id: 'ICE275-03', name: "COCTEL CAPEL ICE 275 ML X 24 - BERRIE", price: 19000, category: "LICORES", image: "catalogo/ICE275.webp" },
  { id: 'ICE275-04', name: "COCTEL CAPEL ICE 275 ML X 24 - MANZANA", price: 19000, category: "LICORES", image: "catalogo/ICE275.webp" },
  { id: 'COR330', name: "CORONA 330ML X18 UNID", price: 14850, category: "CERVEZA", image: "catalogo/COR330.webp" },
  { id: 'COR620', name: "CORONA 620CC X12 UNID", price: 13090, category: "CERVEZA", image: "catalogo/COR620.webp" },
  { id: 'CRISLT', name: "CRISTAL LATA 470CC x 24 unidades", price: 16560, category: "CERVEZA", image: "catalogo/CRISLT.webp" },
  { id: 'CRIS12', name: "CRISTAL LATA 470cc X12UNID", price: 8520, category: "CERVEZA", image: "catalogo/CRIS12.webp" },
  { id: 'LIN', name: "ENCENDEDOR LIN", price: 2100, category: "BEBIDAS", image: "catalogo/LIN.webp" },
  { id: 'ZO-01', name: "ENERGY ZOOM 473 ML x 24 unidades - ZOOM PURPLE", price: 15600, category: "ENERGÃ‰TICAS", image: "catalogo/ZO.webp" },
  { id: 'ZO-02', name: "ENERGY ZOOM 473 ML x 24 unidades - ZOOM WHITE", price: 15600, category: "ENERGÃ‰TICAS", image: "catalogo/ZO.webp" },
  { id: 'ESPAMAR', name: "ESPUMANTE AMARANTA BRUT 12.4g 750", price: 4650, category: "LICORES", image: "catalogo/ESPAMAR.webp" },
  { id: 'ESPCARM', name: "ESPUMANTE CARMEN FK MOSCATO 12g 250", price: 20262, category: "LICORES", image: "catalogo/ESPCARM.webp" },
  { id: 'EXP500', name: "EXPORTACION VINO 500ML", price: 14768, category: "BEBIDAS", image: "catalogo/EXP500.webp" },
  { id: 'EXPRB-01', name: "EXPRESS CCU X30 - PEPSI", price: 11200, category: "BEBIDAS", image: "catalogo/EXPRB.webp" },
  { id: 'EXPRB-02', name: "EXPRESS CCU X30 - PESI ZERO", price: 11200, category: "BEBIDAS", image: "catalogo/EXPRB.webp" },
  { id: 'EXPRB-03', name: "EXPRESS CCU X30 - KEM", price: 11200, category: "BEBIDAS", image: "catalogo/EXPRB.webp" },
  { id: 'EXPRB-04', name: "EXPRESS CCU X30 - BILZ", price: 11200, category: "BEBIDAS", image: "catalogo/EXPRB.webp" },
  { id: 'EXPRB-05', name: "EXPRESS CCU X30 - LIMON SODA", price: 11200, category: "BEBIDAS", image: "catalogo/EXPRB.webp" },
  { id: 'EXPRB-06', name: "EXPRESS CCU X30 - PAP", price: 11200, category: "BEBIDAS", image: "catalogo/EXPRB.webp" },
  { id: 'SXF-01', name: "FASTYLE 630ML X 6UNID - TROPICAL BLUE", price: 7900, category: "BEBIDAS", image: "catalogo/SXF.webp" },
  { id: 'SXF-02', name: "FASTYLE 630ML X 6UNID - FRUTILLA", price: 7900, category: "BEBIDAS", image: "catalogo/SXF.webp" },
  { id: 'SXF-03', name: "FASTYLE 630ML X 6UNID - FRUTILLA KIWI", price: 7900, category: "BEBIDAS", image: "catalogo/SXF.webp" },
  { id: 'FR2-01', name: "Fruna 2.0 LT x 6 unidades - COLA", price: 3490, category: "BEBIDAS", image: "catalogo/FR2.webp" },
  { id: 'FR2-02', name: "Fruna 2.0 LT x 6 unidades - PIÑA", price: 3490, category: "BEBIDAS", image: "catalogo/FR2.webp" },
  { id: 'FR2-03', name: "Fruna 2.0 LT x 6 unidades - PAPAYA", price: 3490, category: "BEBIDAS", image: "catalogo/FR2.webp" },
  { id: 'FR2-04', name: "Fruna 2.0 LT x 6 unidades - NARANJA", price: 3490, category: "BEBIDAS", image: "catalogo/FR2.webp" },
  { id: 'FR2-05', name: "Fruna 2.0 LT x 6 unidades - LIMON SODA", price: 3490, category: "BEBIDAS", image: "catalogo/FR2.webp" },
  { id: 'FR2-06', name: "Fruna 2.0 LT x 6 unidades - FRUTAL", price: 3490, category: "BEBIDAS", image: "catalogo/FR2.webp" },
  { id: 'FR2-07', name: "Fruna 2.0 LT x 6 unidades - GINGER ALE", price: 3490, category: "BEBIDAS", image: "catalogo/FR2.webp" },
  { id: 'FR500-01', name: "Fruna 500ml x 12 unidades - COLA", price: 3590, category: "BEBIDAS", image: "catalogo/FR500.webp" },
  { id: 'FR500-02', name: "Fruna 500ml x 12 unidades - PIÑA", price: 3590, category: "BEBIDAS", image: "catalogo/FR500.webp" },
  { id: 'FR500-03', name: "Fruna 500ml x 12 unidades - PAPAYA", price: 3590, category: "BEBIDAS", image: "catalogo/FR500.webp" },
  { id: 'FR500-04', name: "Fruna 500ml x 12 unidades - NARANJA", price: 3590, category: "BEBIDAS", image: "catalogo/FR500.webp" },
  { id: 'FR500-05', name: "Fruna 500ml x 12 unidades - LIMON SODA", price: 3590, category: "BEBIDAS", image: "catalogo/FR500.webp" },
  { id: 'FR500-06', name: "Fruna 500ml x 12 unidades - FRUTAL", price: 3590, category: "BEBIDAS", image: "catalogo/FR500.webp" },
  { id: 'FR500-07', name: "Fruna 500ml x 12 unidades - GINGER ALE", price: 3590, category: "BEBIDAS", image: "catalogo/FR500.webp" },
  { id: 'GATO1A-01', name: "GATORADE 1LT DESECHABLE x 6 unidades - AZUL", price: 7260, category: "BEBIDAS", image: "catalogo/GATO1A.webp" },
  { id: 'GATO1A-02', name: "GATORADE 1LT DESECHABLE x 6 unidades - ROJO", price: 7260, category: "BEBIDAS", image: "catalogo/GATO1A.webp" },
  { id: 'GATO1A-03', name: "GATORADE 1LT DESECHABLE x 6 unidades - NARANJA", price: 7260, category: "BEBIDAS", image: "catalogo/GATO1A.webp" },
  { id: 'GATO750-01', name: "GATORADE 750ML x 6 unidades - AZUL", price: 5280, category: "BEBIDAS", image: "catalogo/GATO750.webp" },
  { id: 'GATO750-02', name: "GATORADE 750ML x 6 unidades - ROJO", price: 5280, category: "BEBIDAS", image: "catalogo/GATO750.webp" },
  { id: 'GATO750-03', name: "GATORADE 750ML x 6 unidades - NARANJA", price: 5280, category: "BEBIDAS", image: "catalogo/GATO750.webp" },
  { id: 'GINGORD', name: "GIN GORDONS 750 cc", price: 11650, category: "GIN", image: "catalogo/GINGORD.webp" },
  { id: 'TQRAYBOS', name: "GIN TANQUERAY BOSSA NOVA 700cc", price: 16920, category: "GIN", image: "catalogo/TQRAYBOS.webp" },
  { id: 'TQRAYLOND', name: "GIN TANQUERAY LON D 700CC", price: 15690, category: "GIN", image: "catalogo/TQRAYLOND.webp" },
  { id: 'TQRAYROY', name: "GIN TANQUERAY ROYALE 700cc", price: 16920, category: "GIN", image: "catalogo/TQRAYROY.webp" },
  { id: 'TQRAYSEVI', name: "GIN TANQUERAY SEVI 700 cc", price: 16920, category: "GIN", image: "catalogo/TQRAYSEVI.webp" },
  { id: 'H1', name: "HUEVO 1ERA", price: 32000, category: "BEBIDAS", image: "catalogo/H1.webp" },
  { id: 'HEX', name: "HUEVO EXTRA", price: 36000, category: "BEBIDAS", image: "catalogo/HEX.webp" },
  { id: 'IRON-01', name: "ISOTONICA IRONADE 1LT - ROJO", price: 4500, category: "LICORES", image: "catalogo/IRON.webp" },
  { id: 'IRON-02', name: "ISOTONICA IRONADE 1LT - AZUL", price: 4500, category: "LICORES", image: "catalogo/IRON.webp" },
  { id: 'IRON-03', name: "ISOTONICA IRONADE 1LT - NARANJA", price: 4500, category: "LICORES", image: "catalogo/IRON.webp" },
  { id: 'JABAMIX', name: "JABA MIXTA 10 BEBIDAS", price: 10250, category: "PROMOCIONES", image: "catalogo/JABAMIX.webp" },
  { id: 'JAL-01', name: "JUGO ANDINA 340ML X 6UNID - DURAZNO", price: 3900, category: "BEBIDAS", image: "catalogo/JAL.webp" },
  { id: 'JAL-02', name: "JUGO ANDINA 340ML X 6UNID - PERA", price: 3900, category: "BEBIDAS", image: "catalogo/JAL.webp" },
  { id: 'JC2-01', name: "JUGO CYRO 2LT x 6 unidades - PIÑA", price: 4250, category: "BEBIDAS", image: "catalogo/JC2.webp" },
  { id: 'JC2-02', name: "JUGO CYRO 2LT x 6 unidades - NARANJA", price: 4250, category: "BEBIDAS", image: "catalogo/JC2.webp" },
  { id: 'JC2-03', name: "JUGO CYRO 2LT x 6 unidades - FRUTILLA", price: 4250, category: "BEBIDAS", image: "catalogo/JC2.webp" },
  { id: 'JC2-04', name: "JUGO CYRO 2LT x 6 unidades - DURAZNO", price: 4250, category: "BEBIDAS", image: "catalogo/JC2.webp" },
  { id: 'JUMEXM-01', name: "JUMEX 355 X BANDEJA x 24 unidades - PIÑA", price: 15650, category: "BEBIDAS", image: "catalogo/JUMEXM.webp" },
  { id: 'JUMEXM-02', name: "JUMEX 355 X BANDEJA x 24 unidades - PIÑA COCO", price: 15650, category: "BEBIDAS", image: "catalogo/JUMEXM.webp" },
  { id: 'JUMEXM-03', name: "JUMEX 355 X BANDEJA x 24 unidades - MANGO", price: 15650, category: "BEBIDAS", image: "catalogo/JUMEXM.webp" },
  { id: 'JUMEXM-04', name: "JUMEX 355 X BANDEJA x 24 unidades - DURAZNO", price: 15650, category: "BEBIDAS", image: "catalogo/JUMEXM.webp" },
  { id: 'JUMEXM-05', name: "JUMEX 355 X BANDEJA x 24 unidades - PERA", price: 15650, category: "BEBIDAS", image: "catalogo/JUMEXM.webp" },
  { id: 'JUMEXM-06', name: "JUMEX 355 X BANDEJA x 24 unidades - MANZANA", price: 15650, category: "BEBIDAS", image: "catalogo/JUMEXM.webp" },
  { id: 'KAPOF-01', name: "KAPO X24 UNID - PIÑA", price: 5800, category: "BEBIDAS", image: "catalogo/KAPOF.webp" },
  { id: 'KAPOF-02', name: "KAPO X24 UNID - MANZANA", price: 5800, category: "BEBIDAS", image: "catalogo/KAPOF.webp" },
  { id: 'KAPOF-03', name: "KAPO X24 UNID - FRAMBUESA", price: 5800, category: "BEBIDAS", image: "catalogo/KAPOF.webp" },
  { id: 'KAPOF-04', name: "KAPO X24 UNID - NARANJA", price: 5800, category: "BEBIDAS", image: "catalogo/KAPOF.webp" },
  { id: 'LATAK6-01', name: "LATA CCU X 6 UNIDAD. - ´PAP", price: 3780, category: "BEBIDAS", image: "catalogo/LATAK6.webp" },
  { id: 'LATAK6-02', name: "LATA CCU X 6 UNIDAD. - BILZ", price: 3780, category: "BEBIDAS", image: "catalogo/LATAK6.webp" },
  { id: 'LATAK6-03', name: "LATA CCU X 6 UNIDAD. - KEM", price: 3780, category: "BEBIDAS", image: "catalogo/LATAK6.webp" },
  { id: 'LATAK6-04', name: "LATA CCU X 6 UNIDAD. - LIMON", price: 3780, category: "BEBIDAS", image: "catalogo/LATAK6.webp" },
  { id: 'LATAK6-05', name: "LATA CCU X 6 UNIDAD. - PEPSI", price: 3780, category: "BEBIDAS", image: "catalogo/LATAK6.webp" },
  { id: 'LATAK6-06', name: "LATA CCU X 6 UNIDAD. - PEPSI ZERO", price: 3780, category: "BEBIDAS", image: "catalogo/LATAK6.webp" },
  { id: 'LATAK6-07', name: "LATA CCU X 6 UNIDAD. - GINGER", price: 3780, category: "BEBIDAS", image: "catalogo/LATAK6.webp" },
  { id: 'LATAK6-08', name: "LATA CCU X 6 UNIDAD. - CRUSH", price: 3780, category: "BEBIDAS", image: "catalogo/LATAK6.webp" },
  { id: 'LATAK6-09', name: "LATA CCU X 6 UNIDAD. - SEVEN UP", price: 3780, category: "BEBIDAS", image: "catalogo/LATAK6.webp" },
  { id: 'LATAK6-10', name: "LATA CCU X 6 UNIDAD. - KEM EXTREME", price: 3780, category: "BEBIDAS", image: "catalogo/LATAK6.webp" },
  { id: 'ESC710', name: "LATA ESCUDO 710ML X 24 UNID", price: 18960, category: "CERVEZA", image: "catalogo/ESC710.webp" },
  { id: 'MINIC-01', name: "LATA MINI 200ML 6 UNIDAD - COCA COLA", price: 3330, category: "BEBIDAS", image: "catalogo/MINIC.webp" },
  { id: 'MINIC-02', name: "LATA MINI 200ML 6 UNIDAD - COCA COLA ZERO", price: 3330, category: "BEBIDAS", image: "catalogo/MINIC.webp" },
  { id: 'MINIC-03', name: "LATA MINI 200ML 6 UNIDAD - FANTA", price: 3330, category: "BEBIDAS", image: "catalogo/MINIC.webp" },
  { id: 'MINIC-04', name: "LATA MINI 200ML 6 UNIDAD - SPRITE", price: 3330, category: "BEBIDAS", image: "catalogo/MINIC.webp" },
  { id: 'MAL355', name: "MALTIN 355 ML X 24 UNIDAD", price: 27600, category: "BEBIDAS", image: "catalogo/MAL355.webp" },
  { id: 'MONSO6-01', name: "MONSTER 473ML X6 UNID. - MANGO LOCO", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSO6.webp" },
  { id: 'MONSO6-02', name: "MONSTER 473ML X6 UNID. - PIPERLINE PUNSH", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSO6.webp" },
  { id: 'MONSO6-03', name: "MONSTER 473ML X6 UNID. - ZERO ULTRA", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSO6.webp" },
  { id: 'MONSO6-04', name: "MONSTER 473ML X6 UNID. - ULTRA PARADISE", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSO6.webp" },
  { id: 'MONSO6-05', name: "MONSTER 473ML X6 UNID. - ORIGINAL", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSO6.webp" },
  { id: 'MONSO6-06', name: "MONSTER 473ML X6 UNID. - ORIGINAL ZERO", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSO6.webp" },
  { id: 'MONSO6-07', name: "MONSTER 473ML X6 UNID. - RIPPER", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSO6.webp" },
  { id: 'PISAL', name: "PISCO ALTO DEL CARMEN 1LT", price: 6400, category: "PISCO", image: "catalogo/PISAL.webp" },
  { id: 'POWA1-01', name: "POWERADE 1.1LT x 6 unidades - AZUL", price: 7550, category: "BEBIDAS", image: "catalogo/POWA1.webp" },
  { id: 'POWA1-02', name: "POWERADE 1.1LT x 6 unidades - ROJO", price: 7550, category: "BEBIDAS", image: "catalogo/POWA1.webp" },
  { id: 'POWA1-03', name: "POWERADE 1.1LT x 6 unidades - NARANJA", price: 7550, category: "BEBIDAS", image: "catalogo/POWA1.webp" },
  { id: 'PROD002', name: "Pack Cerveza Heineken Lata 6x350cc", price: 4990, category: "CERVEZA", image: "logo.jpg.jpeg" },
  { id: 'PROD006', name: "Papas Fritas Kryzpo Original 130g", price: 1490, category: "LICORES", image: "logo.jpg.jpeg" },
  { id: 'PROD001', name: "Pisco Mistral 35° 1L", price: 6990, category: "LICORES", image: "logo.jpg.jpeg" },
  { id: 'RB355', name: "RED BULL 355CC X 12 UNIDADES", price: 20760, category: "ENERGÃ‰TICAS", image: "catalogo/RB355.webp" },
  { id: 'RB473', name: "RED BULL 473CC X 12 UNIDADES", price: 25920, category: "ENERGÃ‰TICAS", image: "catalogo/RB473.webp" },
  { id: 'RB250', name: "REDBULL 250ML x12 unid", price: 15200, category: "BEBIDAS", image: "catalogo/RB250.webp" },
  { id: 'RSTAR-01', name: "ROCKSTAR 500 ML x 12 unidades - ORIGINAL", price: 11160, category: "BEBIDAS", image: "catalogo/RSTAR.webp" },
  { id: 'RSTAR-02', name: "ROCKSTAR 500 ML x 12 unidades - MANGO POWER", price: 11160, category: "BEBIDAS", image: "catalogo/RSTAR.webp" },
  { id: 'RSTAR-03', name: "ROCKSTAR 500 ML x 12 unidades - SANDIA PUNSH", price: 11160, category: "BEBIDAS", image: "catalogo/RSTAR.webp" },
  { id: 'RONANEJ', name: "RON MADDERO ANEJO 750 cc", price: 6250, category: "RON", image: "catalogo/RONANEJ.webp" },
  { id: 'RONBL', name: "RON MADDERO BLANCO 750 cc", price: 4550, category: "RON", image: "catalogo/RONBL.webp" },
  { id: 'RONDOR1', name: "RON MADDERO DORADO 1LT", price: 5190, category: "RON", image: "catalogo/RONDOR1.webp" },
  { id: 'RONANE', name: "RON MADDERO DORADO 750 cc", price: 4990, category: "RON", image: "catalogo/RONANE.webp" },
  { id: 'ROY470', name: "ROYAL 470 X 24 UNID", price: 18960, category: "CERVEZA", image: "catalogo/ROY470.webp" },
  { id: 'SCOREG-01', name: "SCORE 473ML x 24 unidades - GORILLA", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCOREG.webp" },
  { id: 'SCOREG-02', name: "SCORE 473ML x 24 unidades - FRUIT PUNSH", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCOREG.webp" },
  { id: 'SCOREG-03', name: "SCORE 473ML x 24 unidades - MANGO", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCOREG.webp" },
  { id: 'SCOREG-04', name: "SCORE 473ML x 24 unidades - MOJITO", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCOREG.webp" },
  { id: 'SCOREG-05', name: "SCORE 473ML x 24 unidades - BUBLE GUM", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCOREG.webp" },
  { id: 'SCOREG-06', name: "SCORE 473ML x 24 unidades - ORIGINAL", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCOREG.webp" },
  { id: 'SCOREG-07', name: "SCORE 473ML x 24 unidades - WATER MELON", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCOREG.webp" },
  { id: 'SCOREG-08', name: "SCORE 473ML x 24 unidades - RADICAL WHILE", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCOREG.webp" },
  { id: 'ENER250-01', name: "SCORE ENERGY DRINK 250 ML x 16 unidades - ORIGINAL", price: 13000, category: "ENERGÃ‰TICAS", image: "catalogo/ENER250.webp" },
  { id: 'ENER250-02', name: "SCORE ENERGY DRINK 250 ML x 16 unidades - SANDIA", price: 13000, category: "ENERGÃ‰TICAS", image: "catalogo/ENER250.webp" },
  { id: 'ENER250-03', name: "SCORE ENERGY DRINK 250 ML x 16 unidades - FRUTOS TROPICALES", price: 13000, category: "ENERGÃ‰TICAS", image: "catalogo/ENER250.webp" },
  { id: 'ENERGY-01', name: "SCORE ENERGY DRINK 500 ML x 24 unidades - ORIGINAL", price: 18000, category: "ENERGÃ‰TICAS", image: "catalogo/ENERGY.webp" },
  { id: 'ENERGY-02', name: "SCORE ENERGY DRINK 500 ML x 24 unidades - SANDIA", price: 18000, category: "ENERGÃ‰TICAS", image: "catalogo/ENERGY.webp" },
  { id: 'ENERGY-03', name: "SCORE ENERGY DRINK 500 ML x 24 unidades - FRUTOS TROPICALES", price: 18000, category: "ENERGÃ‰TICAS", image: "catalogo/ENERGY.webp" },
  { id: 'SOL650', name: "SOL 650 x 12 unidades", price: 12000, category: "CERVEZA", image: "catalogo/SOL650.webp" },
  { id: 'SOPA-01', name: "SOPA MOLINOVA 94G X CAJA DE 9 unidades - POLLO", price: 9000, category: "BEBIDAS", image: "catalogo/SOPA.webp" },
  { id: 'SOPA-02', name: "SOPA MOLINOVA 94G X CAJA DE 9 unidades - CARNE", price: 9000, category: "BEBIDAS", image: "catalogo/SOPA.webp" },
  { id: 'SOPA-03', name: "SOPA MOLINOVA 94G X CAJA DE 9 unidades - CARNE PICANTE", price: 9000, category: "BEBIDAS", image: "catalogo/SOPA.webp" },
  { id: 'SOPA-04', name: "SOPA MOLINOVA 94G X CAJA DE 9 unidades - CAMARON", price: 9000, category: "BEBIDAS", image: "catalogo/SOPA.webp" },
  { id: 'AND125DES', name: "SPRITE 1.25 DESECHABLE x 6 unidades", price: 5340, category: "BEBIDAS", image: "catalogo/AND125DES.webp" },
  { id: 'SX', name: "SUEROX 630ML SURTIDO", price: 17880, category: "BEBIDAS", image: "catalogo/SX.webp" },
  { id: 'LIPT15-01', name: "TE LIPTON 1.5 LT DESECHABLE x 6 unidades - LIMON", price: 11526, category: "BEBIDAS", image: "catalogo/LIPT15.webp" },
  { id: 'LIPT15-02', name: "TE LIPTON 1.5 LT DESECHABLE x 6 unidades - DURAZNO", price: 11526, category: "BEBIDAS", image: "catalogo/LIPT15.webp" },
  { id: 'LIPT15-03', name: "TE LIPTON 1.5 LT DESECHABLE x 6 unidades - FRAMBUESA", price: 11526, category: "BEBIDAS", image: "catalogo/LIPT15.webp" },
  { id: 'LIPT15-04', name: "TE LIPTON 1.5 LT DESECHABLE x 6 unidades - TE VERDE MANGO", price: 11526, category: "BEBIDAS", image: "catalogo/LIPT15.webp" },
  { id: 'LIPT15-05', name: "TE LIPTON 1.5 LT DESECHABLE x 6 unidades - TE VERDE LIMON", price: 11526, category: "BEBIDAS", image: "catalogo/LIPT15.webp" },
  { id: 'VIN120M', name: "VINO 120 1.5 LT X6 UNID", price: 18624, category: "BEBIDAS", image: "catalogo/VIN120M.webp" },
  { id: 'VINMED', name: "VINO 120 3 MEDLLA L.HARVEST 12g 750 X3 UNID", price: 12800, category: "BEBIDAS", image: "catalogo/VINMED.webp" },
  { id: 'VMREAL', name: "VINO CARM FK/MREAL CS 13.5g 750 X 3 UNID", price: 12680, category: "BEBIDAS", image: "catalogo/VMREAL.webp" },
  { id: 'VINCAR', name: "VINO FLORESTA CAR 13.3g 750cc", price: 15800, category: "BEBIDAS", image: "catalogo/VINCAR.webp" },
  { id: 'VINCHARDONNAY', name: "VINO FLORESTA CHARDONNAY 13.4g 750CC", price: 16200, category: "BEBIDAS", image: "catalogo/VINCHARDONNAY.webp" },
  { id: 'VINREAL', name: "VINO M. REAL RVA X2 CS-MER 13.5G 750CC", price: 7170, category: "BEBIDAS", image: "catalogo/VINREAL.webp" },
  { id: 'VITSG16-01', name: "VITAL 1.6LT - CON GAS", price: 4866, category: "AGUA", image: "catalogo/VITSG16.webp" },
  { id: 'VITSG16-02', name: "VITAL 1.6LT - SIN GAS", price: 4866, category: "AGUA", image: "catalogo/VITSG16.webp" },
  { id: 'VITP', name: "VITAL 1LT x 6 unidades", price: 8280, category: "AGUA", image: "catalogo/VITP.webp" },
  { id: 'VIT330-01', name: "VITAL 330 ML VIDRIO X 12UNID. - CON GAS", price: 8280, category: "AGUA", image: "catalogo/VIT330.webp" },
  { id: 'VIT330-02', name: "VITAL 330 ML VIDRIO X 12UNID. - SIN GAS", price: 8280, category: "AGUA", image: "catalogo/VIT330.webp" },
  { id: 'VITSG600-01', name: "VITAL 600ML x 12 unidades - CON GAS", price: 5940, category: "AGUA", image: "catalogo/VITSG600.webp" },
  { id: 'VITSG600-02', name: "VITAL 600ML x 12 unidades - SIN GAS", price: 5940, category: "AGUA", image: "catalogo/VITSG600.webp" },
  { id: 'PROD003', name: "Vino Casillero del Diablo Cabernet Sauvignon 750cc", price: 4490, category: "BEBIDAS", image: "logo.jpg.jpeg" },
  { id: 'WATTSD-01', name: "WATTS 1.5LT DESECHABLE x 6 unidades - DURAZNO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-02', name: "WATTS 1.5LT DESECHABLE x 6 unidades - NARANJA", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-03', name: "WATTS 1.5LT DESECHABLE x 6 unidades - PIÑA", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-04', name: "WATTS 1.5LT DESECHABLE x 6 unidades - DURAZNO CERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-05', name: "WATTS 1.5LT DESECHABLE x 6 unidades - NARANJA ZERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-06', name: "WATTS 1.5LT DESECHABLE x 6 unidades - PIÑA ZERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-07', name: "WATTS 1.5LT DESECHABLE x 6 unidades - TUTIFRUTILLA ORIGINAL", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-08', name: "WATTS 1.5LT DESECHABLE x 6 unidades - TUTIFRUTILLA ZERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-09', name: "WATTS 1.5LT DESECHABLE x 6 unidades - NARANJA MANZANA", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-10', name: "WATTS 1.5LT DESECHABLE x 6 unidades - MANGO ZERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-11', name: "WATTS 1.5LT DESECHABLE x 6 unidades - MARACUYA ZERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-12', name: "WATTS 1.5LT DESECHABLE x 6 unidades - NARANJA PLATANO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-13', name: "WATTS 1.5LT DESECHABLE x 6 unidades - TUTIKIWI", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-14', name: "WATTS 1.5LT DESECHABLE x 6 unidades - TUTIARANDANO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-15', name: "WATTS 1.5LT DESECHABLE x 6 unidades - DAMASCO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WATTSD-16', name: "WATTS 1.5LT DESECHABLE x 6 unidades - MANZANA", price: 9120, category: "BEBIDAS", image: "catalogo/WATTSD.webp" },
  { id: 'WB300-01', name: "WATTS BOCA ANCHA 300 ML x 24 unidades - DURAZNO", price: 19920, category: "BEBIDAS", image: "catalogo/WB300.webp" },
  { id: 'WB300-02', name: "WATTS BOCA ANCHA 300 ML x 24 unidades - NARANJA", price: 19920, category: "BEBIDAS", image: "catalogo/WB300.webp" },
  { id: 'WB300-03', name: "WATTS BOCA ANCHA 300 ML x 24 unidades - PIÑA", price: 19920, category: "BEBIDAS", image: "catalogo/WB300.webp" },
  { id: 'WB300-04', name: "WATTS BOCA ANCHA 300 ML x 24 unidades - TUTIFRUTILLA", price: 19920, category: "BEBIDAS", image: "catalogo/WB300.webp" },
  { id: 'WHISBUCH', name: "WHISKY BUCHANANS DELUXE 750 CC", price: 24230, category: "WHISKY", image: "catalogo/WHISBUCH.webp" },
  { id: 'WHISKEY', name: "WHISKY JACK DANIEL 50ML", price: 2600, category: "WHISKY", image: "catalogo/WHISKEY.webp" },
  { id: 'WHISBLACK', name: "WHISKY JW BLACK 750 ml - BLACK 200ML", price: 28990, category: "WHISKY", image: "catalogo/WHISBLACK.webp" },
  { id: 'WHISGOLD', name: "WHISKY JW GOLD LABEL 750 ml - Copa", price: 56000, category: "WHISKY", image: "catalogo/WHISGOLD.webp" },
  { id: 'WHISRED', name: "WHISKY RED LABEL 750 CC", price: 9990, category: "WHISKY", image: "catalogo/WHISRED.webp" },
  { id: 'WHISSAND', name: "WHISKY SANDY MAC 1LT", price: 12500, category: "WHISKY", image: "catalogo/WHISSAND.webp" },
  { id: 'WHISHOR', name: "WHISKY WHITE HOR 750 cc 40G X1", price: 7396, category: "WHISKY", image: "catalogo/WHISHOR.webp" },
  { id: 'BIGCOLA473', name: "BIG COLA LATA 473ML x 6 unidades", price: 3180, category: "BEBIDAS", image: "catalogo/BIGCOLA473.jpeg" },
  { id: 'BIGUVA17', name: "BIG UVA 1.7L x 6 unidades", price: 5250, category: "BEBIDAS", image: "catalogo/BIGUVA17.jpeg" },
  { id: 'ALOE15-01', name: "ALOE VERA 1.5L x 12 unidades - ORIGINAL", price: 20280, category: "BEBIDAS", image: "catalogo/ALOE15.jpeg" },
  { id: 'ALOE15-02', name: "ALOE VERA 1.5L x 12 unidades - PIÑA", price: 20280, category: "BEBIDAS", image: "catalogo/ALOE15.jpeg" },
  { id: 'ALOE15-03', name: "ALOE VERA 1.5L x 12 unidades - FRUTILLA", price: 20280, category: "BEBIDAS", image: "catalogo/ALOE15.jpeg" },
  { id: 'SCOREW473-01', name: "SCORE WATER 473ML x 24 unidades - ALOE VERA", price: 18000, category: "ENERGÉTICAS", image: "catalogo/SCOREW473.jpeg" },
  { id: 'SCOREW473-02', name: "SCORE WATER 473ML x 24 unidades - SIN GAS", price: 18000, category: "ENERGÉTICAS", image: "catalogo/SCOREW473.jpeg" },
  { id: 'SCOREW473-03', name: "SCORE WATER 473ML x 24 unidades - CON GAS", price: 18000, category: "ENERGÉTICAS", image: "catalogo/SCOREW473.jpeg" },
  { id: 'ZOOM12-01', name: "ENERGY ZOOM 473ML x 12 unidades - WHITE", price: 7800, category: "ENERGÉTICAS", image: "catalogo/ZOOM12.jpeg" },
  { id: 'ZOOM12-02', name: "ENERGY ZOOM 473ML x 12 unidades - PURPLE", price: 7800, category: "ENERGÉTICAS", image: "catalogo/ZOOM12.jpeg" },
  { id: 'EXPRESS24-01', name: "COCA COLA EXPRESS 250ML x 24 unidades - COCA COLA", price: 10104, category: "BEBIDAS", image: "catalogo/EXPRESS24.jpeg" },
  { id: 'EXPRESS24-02', name: "COCA COLA EXPRESS 250ML x 24 unidades - COCA COLA ZERO", price: 10104, category: "BEBIDAS", image: "catalogo/EXPRESS24.jpeg" },
  { id: 'EXPRESS24-03', name: "COCA COLA EXPRESS 250ML x 24 unidades - FANTA", price: 10104, category: "BEBIDAS", image: "catalogo/EXPRESS24.jpeg" },
  { id: 'EXPRESS24-04', name: "COCA COLA EXPRESS 250ML x 24 unidades - SPRITE", price: 10104, category: "BEBIDAS", image: "catalogo/EXPRESS24.jpeg" },
  { id: 'POWA850-01', name: "POWERADE 850ML x 6 unidades - AZUL", price: 5850, category: "BEBIDAS", image: "catalogo/POWA850.jpeg" },
  { id: 'POWA850-02', name: "POWERADE 850ML x 6 unidades - ROJO", price: 5850, category: "BEBIDAS", image: "catalogo/POWA850.jpeg" },
  { id: 'MINI250-01', name: "COCA COLA MINI 250ML x 6 unidades - COCA COLA", price: 6200, category: "BEBIDAS", image: "catalogo/MINI250.jpeg" },
  { id: 'MINI250-02', name: "COCA COLA MINI 250ML x 6 unidades - COCA COLA ZERO", price: 6200, category: "BEBIDAS", image: "catalogo/MINI250.jpeg" },
  { id: 'MINI250-03', name: "COCA COLA MINI 250ML x 6 unidades - FANTA", price: 6200, category: "BEBIDAS", image: "catalogo/MINI250.jpeg" },
  { id: 'MINI250-04', name: "COCA COLA MINI 250ML x 6 unidades - SPRITE", price: 6200, category: "BEBIDAS", image: "catalogo/MINI250.jpeg" }
];
