const catalogoProductos = [
  { id: 'LIFE3-01', name: "AGUA LIFE 3 LT x 6 unidades - CON GAS", price: 3590, category: "AGUA", image: "catalogo/AGUA_LIFE_3L_BLANCO.jpg" },
  { id: 'LIFE3-02', name: "AGUA LIFE 3 LT x 6 unidades - SIN GAS", price: 3590, category: "AGUA", image: "catalogo/AGUA_LIFE_3L_BLANCO.jpg" },
  { id: 'MASC-01', name: "AGUA MAS 600ML X12 UNID - UVA SIN GAS", price: 10516, category: "AGUA", image: "catalogo/AGUA_MAS_600ML_X12_UNID_-_UVA_SIN_GAS.webp" },
  { id: 'MASC-02', name: "AGUA MAS 600ML X12 UNID - MANZANASIN GAS", price: 10516, category: "AGUA", image: "catalogo/AGUA_MAS_600ML_X12_UNID_-_MANZANASIN_GAS.webp" },
  { id: 'MASC-03', name: "AGUA MAS 600ML X12 UNID - PERA SIN GAS", price: 10516, category: "AGUA", image: "catalogo/AGUA_MAS_600ML_X12_UNID_-_PERA_SIN_GAS.webp" },
  { id: 'MASC-04', name: "AGUA MAS 600ML X12 UNID - GRANADA SIN GAS", price: 10516, category: "AGUA", image: "catalogo/AGUA_MAS_600ML_X12_UNID_-_GRANADA_SIN_GAS.webp" },
  { id: 'MASC-05', name: "AGUA MAS 600ML X12 UNID - MANGO MARACUYA SIN GAS", price: 10516, category: "AGUA", image: "catalogo/AGUA_MAS_600ML_X12_UNID_-_MANGO_MARACUYA_SIN_GAS.jpg" },
  { id: 'MASC-06', name: "AGUA MAS 600ML X12 UNID - CITRUS CON GAS", price: 10516, category: "AGUA", image: "catalogo/AGUA_MAS_600ML_X12_UNID_-_CITRUS_CON_GAS.webp" },
  { id: 'MASC-07', name: "AGUA MAS 600ML X12 UNID - FRUTOS DEL BOSUQE CON GAS", price: 10516, category: "AGUA", image: "catalogo/AGUA_MAS_600ML_X12_UNID_-_FRUTOS_DEL_BOSUQE_CON_GAS.jpg" },
  { id: 'MASC-08', name: "AGUA MAS 600ML X12 UNID - LIMONADA FRAMBUESA", price: 10516, category: "AGUA", image: "catalogo/AGUA_MAS_600ML_X12_UNID_-_LIMONADA_FRAMBUESA.webp" },
  { id: 'NEST15', name: "AGUA MINERAL NESTLE PURE LIFE 1.5L", price: 1500, category: "AGUA", image: "catalogo/NEST15.webp" },
  { id: 'ALOEO-01', name: "ALOE VERA 500ML X CAJA - ORIGINAL", price: 17952, category: "BEBIDAS", image: "catalogo/ALOE_VERA_500ML_X_CAJA_-_PINA.jpg" },
  { id: 'ALOEO-02', name: "ALOE VERA 500ML X CAJA - PIÑA", price: 17952, category: "BEBIDAS", image: "catalogo/ALOE_VERA_500ML_X_CAJA_-_PINA.jpg" },
  { id: 'ALOEO-03', name: "ALOE VERA 500ML X CAJA - FRUTILLA", price: 17952, category: "BEBIDAS", image: "catalogo/ALOE_VERA_500ML_X_CAJA_-_FRUTILLA.webp" },
  { id: 'ALOEO-04', name: "ALOE VERA 500ML X CAJA - MANGO", price: 17952, category: "BEBIDAS", image: "catalogo/ALOE_VERA_500ML_X_CAJA_-_MANGO.avif" },
  { id: 'ALOEO-05', name: "ALOE VERA 500ML X CAJA - DURAZNO", price: 17952, category: "BEBIDAS", image: "catalogo/ALOE_VERA_500ML_X_CAJA_-_DURAZNO.jpg" },
  { id: 'ALOEO-06', name: "ALOE VERA 500ML X CAJA - GRANADA", price: 17952, category: "BEBIDAS", image: "catalogo/ALOE_VERA_500ML_X_CAJA_-_GRANADA.webp" },
  { id: 'ALOEO-07', name: "ALOE VERA 500ML X CAJA - COCO", price: 17952, category: "BEBIDAS", image: "catalogo/ALOE_VERA_500ML_X_CAJA_-_COCO.jpg" },
  { id: 'AND400-01', name: "ANDINA DEL VALLE 400ML x 6 unidades - DURAZNO", price: 5040, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_400ML_x_6_unidades_-_DURAZNO.png" },
  { id: 'AND400-02', name: "ANDINA DEL VALLE 400ML x 6 unidades - NARANJA", price: 5040, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_400ML_x_6_unidades_-_NARANJA.png" },
  { id: 'AND400-03', name: "ANDINA DEL VALLE 400ML x 6 unidades - PIÑA", price: 5040, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_400ML_x_6_unidades_-_PINA.png" },
  { id: 'AND400-04', name: "ANDINA DEL VALLE 400ML x 6 unidades - TUTIFRUTILLA", price: 5040, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_400ML_x_6_unidades_-_TUTIFRUTILLA.png" },
  { id: 'ANDVA15-01', name: "ANDINA DEL VALLE DESECHABLE x 6 unidades - DURAZNO", price: 6540, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_DESECHABLE_x_6_unidades_-_DURAZNO.png" },
  { id: 'ANDVA15-02', name: "ANDINA DEL VALLE DESECHABLE x 6 unidades - TUTIFRUTILLA", price: 6540, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_DESECHABLE_x_6_unidades_-_TUTIFRUTILLA.png" },
  { id: 'ANDVA15-03', name: "ANDINA DEL VALLE DESECHABLE x 6 unidades - NARANJA", price: 6540, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_DESECHABLE_x_6_unidades_-_NARANJA.png" },
  { id: 'ANDVA15-04', name: "ANDINA DEL VALLE DESECHABLE x 6 unidades - PIÑA", price: 6540, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_DESECHABLE_x_6_unidades_-_PINA.png" },
  { id: 'ANDVA15-05', name: "ANDINA DEL VALLE DESECHABLE x 6 unidades - DAMASCO", price: 6540, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_DESECHABLE_x_6_unidades_-_DAMASCO.png" },
  { id: 'ANDMANLATA', name: "ANDINA DEL VALLE MANZANA LATA 340ML X6", price: 4200, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_MANZANA_LATA_340ML_X6.png" },
  { id: 'ANDMULTI', name: "ANDINA DEL VALLE MULTI-FRUTILLA 1.5L", price: 1800, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_MULTI-FRUTILLA_1.5L.png" },
  { id: 'ANDPACK', name: "ANDINA DEL VALLE PACK SURTIDO", price: 4500, category: "BEBIDAS", image: "catalogo/ANDINA_DEL_VALLE_PACK_SURTIDO.jpg" },
  { id: 'ARROZ', name: "ARROZ MANGA 10 UNID", price: 6950, category: "BEBIDAS", image: "catalogo/ARROZ.webp" },
  { id: 'BAV470', name: "BAVARIA 470 ML X24 UNID", price: 12240, category: "CERVEZA", image: "catalogo/BAV470.webp" },
  { id: 'BEN3-01', name: "BENEDICTINO 3LT x 6 unidades - CON GAS", price: 6900, category: "AGUA", image: "catalogo/BENEDICTINO 3LT x 6 unidades - CON GAS.png" },
  { id: 'BEN3-02', name: "BENEDICTINO 3LT x 6 unidades - SIN GAS", price: 6900, category: "AGUA", image: "catalogo/SCORE_WATER_473ML_x_24_unidades_-_SIN_GAS.jpg" },
  { id: 'BEN5-01', name: "BENEDICTINO 500ML x 12 unidades - CON GAS", price: 4680, category: "AGUA", image: "catalogo/CACHANTUN_500ML_x_12_unidades_-_STRONG_GAS.avif" },
  { id: 'BEN5-02', name: "BENEDICTINO 500ML x 12 unidades - SIN GAS", price: 4680, category: "AGUA", image: "catalogo/CACHANTUN_500ML_x_12_unidades_-_STRONG_GAS.avif" },
  { id: 'BOMB200-01', name: "BOMBILLIN 200CC X24 - DURAZNO", price: 6480, category: "BEBIDAS", image: "catalogo/BOMBILLIN_200CC_X24_-_DURAZNO.png" },
  { id: 'BOMB200-02', name: "BOMBILLIN 200CC X24 - PIÑA", price: 6480, category: "BEBIDAS", image: "catalogo/BOMBILLIN_200CC_X24_-_PINA.png" },
  { id: 'BOMB200-03', name: "BOMBILLIN 200CC X24 - NARANJA", price: 6480, category: "BEBIDAS", image: "catalogo/BOMBILLIN_200CC_X24_-_NARANJA.png" },
  { id: 'BOMB200-04', name: "BOMBILLIN 200CC X24 - MULTIFRUTILLA", price: 6480, category: "BEBIDAS", image: "catalogo/BOMBILLIN_200CC_X24_-_MULTIFRUTILLA.png" },
  { id: 'BOMB200-05', name: "BOMBILLIN 200CC X24 - MANZANA", price: 6480, category: "BEBIDAS", image: "catalogo/BOMBILLIN_200CC_X24_-_PINA.png" },
  { id: 'PROD004', name: "Bebida Coca Cola Original 2.5L", price: 1890, category: "LICORES", image: "catalogo/Bebida_Coca_Cola_Original_2.5L.avif" },
  { id: 'PROD005', name: "Bebida Energética Red Bull 250cc", price: 1690, category: "ENERGÉTICAS", image: "catalogo/Bebida_Energética_Red_Bull_250cc.jpg" },
  { id: 'CATUNSG16-01', name: "CACHANTUN 1.6 LT DESECHABLE x 6 unidades - CON GAS", price: 5520, category: "AGUA", image: "catalogo/CACHANTUN 1.6 LT DESECHABLE x 6 unidades - CON GAS.webp" },
  { id: 'CATUNSG16-02', name: "CACHANTUN 1.6 LT DESECHABLE x 6 unidades - SIN GAS", price: 5520, category: "AGUA", image: "catalogo/CACHANTUN_MAS_1.6_LT_DESECHABLE_x_6_unidades_-_UVA_SIN_GAS.jpg" },
  { id: 'CATUNSG16-03', name: "CACHANTUN 1.6 LT DESECHABLE x 6 unidades - STRONG GAS", price: 5520, category: "AGUA", image: "catalogo/CACHANTUN_1.6_LT_DESECHABLE_x_6_unidades_-_STRONG_GAS.webp" },
  { id: 'CATUNSG16-04', name: "CACHANTUN 1.6 LT DESECHABLE x 6 unidades - LIGTH GAS", price: 5520, category: "AGUA", image: "catalogo/CACHANTUN_1.6_LT_DESECHABLE_x_6_unidades_-_LIGTH_GAS.avif" },
  { id: 'CATUNSG25-01', name: "CACHANTUN 2.5LT DESECHABLE x 6 unidades - CON GAS", price: 6540, category: "AGUA", image: "catalogo/CACHANTUN_MAS_1.6_LT_DESECHABLE_x_6_unidades_-_CITRUS_CON_GAS.webp" },
  { id: 'CATUNSG25-02', name: "CACHANTUN 2.5LT DESECHABLE x 6 unidades - SIN GAS", price: 6540, category: "AGUA", image: "catalogo/CACHANTUN_MAS_1.6_LT_DESECHABLE_x_6_unidades_-_UVA_SIN_GAS.jpg" },
  { id: 'CATUNSG5-01', name: "CACHANTUN 500ML x 12 unidades - CON GAS", price: 4000, category: "AGUA", image: "catalogo/CACHANTUN 500ML x 12 unidades - CON GAS.webp" },
  { id: 'CATUNSG5-02', name: "CACHANTUN 500ML x 12 unidades - SIN GAS", price: 4000, category: "AGUA", image: "catalogo/CACHANTUN 500ML x 12 unidades - SIN GAS.webp" },
  { id: 'CATUNSG5-03', name: "CACHANTUN 500ML x 12 unidades - STRONG GAS", price: 4000, category: "AGUA", image: "catalogo/CACHANTUN_500ML_x_12_unidades_-_STRONG_GAS.avif" },
  { id: 'CATUNSG5-04', name: "CACHANTUN 500ML x 12 unidades - LIGTH GAS", price: 4000, category: "AGUA", image: "catalogo/CACHANTUN_500ML_x_12_unidades_-_LIGTH_GAS.webp" },
  { id: 'MASP-01', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - UVA SIN GAS", price: 7521, category: "AGUA", image: "catalogo/CACHANTUN_MAS_1.6_LT_DESECHABLE_x_6_unidades_-_UVA_SIN_GAS.jpg" },
  { id: 'MASP-02', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - MANZANASIN GAS", price: 7521, category: "AGUA", image: "catalogo/CACHANTUN_MAS_1.6_LT_DESECHABLE_x_6_unidades_-_MANZANASIN_GAS.jpg" },
  { id: 'MASP-03', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - PERA SIN GAS", price: 7521, category: "AGUA", image: "catalogo/CACHANTUN_MAS_1.6_LT_DESECHABLE_x_6_unidades_-_PERA_SIN_GAS.jpg" },
  { id: 'MASP-04', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - GRANADA SIN GAS", price: 7521, category: "AGUA", image: "catalogo/CACHANTUN_MAS_1.6_LT_DESECHABLE_x_6_unidades_-_GRANADA_SIN_GAS.jpg" },
  { id: 'MASP-05', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - MANGO MARACUYA SIN GAS", price: 7521, category: "AGUA", image: "catalogo/CACHANTUN_MAS_1.6_LT_DESECHABLE_x_6_unidades_-_MANGO_MARACUYA_SIN_GAS.jpg" },
  { id: 'MASP-06', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - CITRUS CON GAS", price: 7521, category: "AGUA", image: "catalogo/CACHANTUN_MAS_1.6_LT_DESECHABLE_x_6_unidades_-_CITRUS_CON_GAS.webp" },
  { id: 'MASP-07', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - FRUTOS DEL BOSUQE CON GAS", price: 7521, category: "AGUA", image: "catalogo/CACHANTUN_MAS_1.6_LT_DESECHABLE_x_6_unidades_-_FRUTOS_DEL_BOSUQE_CON_GAS.webp" },
  { id: 'MASP-08', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades - LIMONADA FRAMBUESA", price: 7521, category: "AGUA", image: "catalogo/CACHANTUN_MAS_1.6_LT_DESECHABLE_x_6_unidades_-_LIMONADA_FRAMBUESA.webp" },
  { id: 'KFE-01', name: "CAFE HELADO NESCAFE X 6 UNID. - LATE", price: 9300, category: "BEBIDAS", image: "catalogo/CAFE_HELADO_NESCAFE_X_6_UNID._-_LATE.webp" },
  { id: 'KFE-02', name: "CAFE HELADO NESCAFE X 6 UNID. - MOCKA", price: 9300, category: "BEBIDAS", image: "catalogo/CAFE_HELADO_NESCAFE_X_6_UNID._-_MOCKA.webp" },
  { id: 'KFE-03', name: "CAFE HELADO NESCAFE X 6 UNID. - ORIGINAL", price: 9300, category: "BEBIDAS", image: "catalogo/CAFE_HELADO_NESCAFE_X_6_UNID._-_MOCKA.webp" },
  { id: 'CCU125DES-01', name: "CCU 1.25 DESECHABLE - KEM", price: 5760, category: "BEBIDAS", image: "catalogo/CCU_1.25_DESECHABLE_-_KEM.webp" },
  { id: 'CCU125DES-02', name: "CCU 1.25 DESECHABLE - LIMON", price: 5760, category: "BEBIDAS", image: "catalogo/CCU_1.25_DESECHABLE_-_LIMON.webp" },
  { id: 'CCU125DES-03', name: "CCU 1.25 DESECHABLE - BILZ", price: 5760, category: "BEBIDAS", image: "catalogo/CCU_1.25_DESECHABLE_-_BILZ.webp" },
  { id: 'CCU125DES-04', name: "CCU 1.25 DESECHABLE - PAP", price: 5760, category: "BEBIDAS", image: "catalogo/CCU_1.25_DESECHABLE_-_PAP.webp" },
  { id: 'CCU125DES-05', name: "CCU 1.25 DESECHABLE - PEPSI", price: 5760, category: "BEBIDAS", image: "catalogo/CCU_1.25_DESECHABLE_-_PEPSI.webp" },
  { id: 'CCU125DES-06', name: "CCU 1.25 DESECHABLE - PEPSI ZERO", price: 5760, category: "BEBIDAS", image: "catalogo/CCU_1.25_DESECHABLE_-_PEPSI_ZERO.webp" },
  { id: 'L125_MIX', name: "JABA CCU 1.25LT RETORNABLE x 12 unidades", price: 12990, category: "RETORNABLE", image: "catalogo/JABA_COCA_COLA_1.25_RETORNABLE_x_10_unidades.jpg", isCustom: true },
  { id: 'L25-01', name: "CCU 2.5 LT RETORNABLE x 6 unidades - ´PAP", price: 9498, category: "RETORNABLE", image: "catalogo/CCU_2.5_LT_RETORNABLE_x_6_unidades_-_´PAP.avif" },
  { id: 'L25-02', name: "CCU 2.5 LT RETORNABLE x 6 unidades - BILZ", price: 9498, category: "RETORNABLE", image: "catalogo/CCU_2.5_LT_RETORNABLE_x_6_unidades_-_BILZ.avif" },
  { id: 'L25-03', name: "CCU 2.5 LT RETORNABLE x 6 unidades - KEM", price: 9498, category: "RETORNABLE", image: "catalogo/CCU_2.5_LT_RETORNABLE_x_6_unidades_-_KEM.png" },
  { id: 'L25-04', name: "CCU 2.5 LT RETORNABLE x 6 unidades - LIMON", price: 9498, category: "RETORNABLE", image: "catalogo/CCU_2.5_LT_RETORNABLE_x_6_unidades_-_LIMON.jpg" },
  { id: 'L25-05', name: "CCU 2.5 LT RETORNABLE x 6 unidades - PEPSI", price: 9498, category: "RETORNABLE", image: "catalogo/CCU_2.5_LT_RETORNABLE_x_6_unidades_-_PEPSI.png" },
  { id: 'L25-06', name: "CCU 2.5 LT RETORNABLE x 6 unidades - PEPSI ZERO", price: 9498, category: "RETORNABLE", image: "catalogo/CCU_2.5_LT_RETORNABLE_x_6_unidades_-_PEPSI_ZERO.webp" },
  { id: 'L25-07', name: "CCU 2.5 LT RETORNABLE x 6 unidades - GINGER", price: 9498, category: "RETORNABLE", image: "catalogo/CCU_2.5_LT_RETORNABLE_x_6_unidades_-_GINGER.webp" },
  { id: 'L25-08', name: "CCU 2.5 LT RETORNABLE x 6 unidades - CRUSH", price: 9498, category: "RETORNABLE", image: "catalogo/CCU_2.5_LT_RETORNABLE_x_6_unidades_-_CRUSH.jpg" },
  { id: 'L2_MIX', name: "JABA CCU 2LT RETORNABLE x 9 unidades", price: 13545, category: "RETORNABLE", image: "catalogo/JABA_COCA_COLA_2LT_RETORNABLE_x_8_unidades.webp", isCustom: true },
  { id: 'L3-01', name: "CCU 3LT DESECHABLE x 6 unidades - ´PAP", price: 12080, category: "BEBIDAS", image: "catalogo/CCU_3LT_DESECHABLE_x_6_unidades_-_´PAP.webp" },
  { id: 'L3-02', name: "CCU 3LT DESECHABLE x 6 unidades - BILZ", price: 12080, category: "BEBIDAS", image: "catalogo/CCU_3LT_DESECHABLE_x_6_unidades_-_BILZ.png" },
  { id: 'L3-03', name: "CCU 3LT DESECHABLE x 6 unidades - KEM", price: 12080, category: "BEBIDAS", image: "catalogo/CCU_3LT_DESECHABLE_x_6_unidades_-_KEM.webp" },
  { id: 'L3-04', name: "CCU 3LT DESECHABLE x 6 unidades - LIMON", price: 12080, category: "BEBIDAS", image: "catalogo/CCU_3LT_DESECHABLE_x_6_unidades_-_LIMON.png" },
  { id: 'L3-05', name: "CCU 3LT DESECHABLE x 6 unidades - PEPSI", price: 12080, category: "BEBIDAS", image: "catalogo/CCU_3LT_DESECHABLE_x_6_unidades_-_PEPSI.jpg" },
  { id: 'L3-06', name: "CCU 3LT DESECHABLE x 6 unidades - PEPSI ZERO", price: 12080, category: "BEBIDAS", image: "catalogo/CCU_3LT_DESECHABLE_x_6_unidades_-_PEPSI_ZERO.png" },
  { id: 'L3-07', name: "CCU 3LT DESECHABLE x 6 unidades - GINGER", price: 12080, category: "BEBIDAS", image: "catalogo/CCU_3LT_DESECHABLE_x_6_unidades_-_GINGER.png" },
  { id: 'L3-08', name: "CCU 3LT DESECHABLE x 6 unidades - CRUSH", price: 12080, category: "BEBIDAS", image: "catalogo/CCU_3LT_DESECHABLE_x_6_unidades_-_CRUSH.png" },
  { id: 'L3-09', name: "CCU 3LT DESECHABLE x 6 unidades - SEVEN UP", price: 12080, category: "BEBIDAS", image: "catalogo/CCU_3LT_DESECHABLE_x_6_unidades_-_SEVEN_UP.jpg" },
  { id: 'CCU600-01', name: "CCU 600ML DESECHABLE x 12 unidades - PEPSI", price: 10200, category: "BEBIDAS", image: "catalogo/CCU_600ML_DESECHABLE_x_12_unidades_-_PEPSI.jpg" },
  { id: 'CCU600-02', name: "CCU 600ML DESECHABLE x 12 unidades - PESI ZERO", price: 10200, category: "BEBIDAS", image: "catalogo/CCU_600ML_DESECHABLE_x_12_unidades_-_PESI_ZERO.jfif" },
  { id: 'CCU600-03', name: "CCU 600ML DESECHABLE x 12 unidades - KEM", price: 10200, category: "BEBIDAS", image: "catalogo/CCU_600ML_DESECHABLE_x_12_unidades_-_KEM.webp" },
  { id: 'CCU600-04', name: "CCU 600ML DESECHABLE x 12 unidades - BILZ", price: 10200, category: "BEBIDAS", image: "catalogo/CCU_600ML_DESECHABLE_x_12_unidades_-_BILZ.jpeg" },
  { id: 'CCU600-05', name: "CCU 600ML DESECHABLE x 12 unidades - LIMON SODA", price: 10200, category: "BEBIDAS", image: "catalogo/CCU_600ML_DESECHABLE_x_12_unidades_-_LIMON_SODA.jfif" },
  { id: 'CCU600-06', name: "CCU 600ML DESECHABLE x 12 unidades - GINGER", price: 10200, category: "BEBIDAS", image: "catalogo/CCU_600ML_DESECHABLE_x_12_unidades_-_GINGER.webp" },
  { id: 'CCU600-07', name: "CCU 600ML DESECHABLE x 12 unidades - CRUSH", price: 10200, category: "BEBIDAS", image: "catalogo/CCU_600ML_DESECHABLE_x_12_unidades_-_CRUSH.webp" },
  { id: 'CCU600-08', name: "CCU 600ML DESECHABLE x 12 unidades - PAP", price: 10200, category: "BEBIDAS", image: "catalogo/CCU_600ML_DESECHABLE_x_12_unidades_-_PAP.webp" },
  { id: 'AND15DES-01', name: "COCA COLA 1.5 LT DESECHABLE x 6 unidades - COCA COLA", price: 9888, category: "BEBIDAS", image: "catalogo/COCA_COLA_1.5_LT_DESECHABLE_x_6_unidades_-_COCA_COLA.webp" },
  { id: 'AND15DES-02', name: "COCA COLA 1.5 LT DESECHABLE x 6 unidades - COCA COLA ZERO", price: 9888, category: "BEBIDAS", image: "catalogo/COCA_COLA_1.5_LT_DESECHABLE_x_6_unidades_-_COCA_COLA_ZERO.png" },
  { id: 'AND15DES-03', name: "COCA COLA 1.5 LT DESECHABLE x 6 unidades - FANTA", price: 9888, category: "BEBIDAS", image: "catalogo/COCA_COLA_1.5_LT_DESECHABLE_x_6_unidades_-_FANTA.webp" },
  { id: 'AND15DES-04', name: "COCA COLA 1.5 LT DESECHABLE x 6 unidades - SPRITE", price: 9888, category: "BEBIDAS", image: "catalogo/COCA_COLA_1.5_LT_DESECHABLE_x_6_unidades_-_SPRITE.jpg" },
  { id: 'AND15DES-05', name: "COCA COLA 1.5 LT DESECHABLE x 6 unidades - INCA COLA", price: 9888, category: "BEBIDAS", image: "catalogo/COCA_COLA_1.5_LT_DESECHABLE_x_6_unidades_-_INCA_COLA.jpg" },
  { id: 'AND125_MIX', name: "JABA COCA COLA 1.25 RETORNABLE x 10 unidades", price: 10250, category: "RETORNABLE", image: "catalogo/JABA_COCA_COLA_1.25_RETORNABLE_x_10_unidades.jpg", isCustom: true },
  { id: 'AND2_MIX', name: "JABA COCA COLA 2LT RETORNABLE x 8 unidades", price: 11880, category: "RETORNABLE", image: "catalogo/JABA_COCA_COLA_2LT_RETORNABLE_x_8_unidades.webp", isCustom: true },
  { id: 'AND3DES-01', name: "COCA COLA 3LT DESECHABLE x 6 unidades - COCA COLA", price: 14850, category: "BEBIDAS", image: "catalogo/COCA_COLA_3LT_DESECHABLE_x_6_unidades_-_COCA_COLA.webp" },
  { id: 'AND3DES-02', name: "COCA COLA 3LT DESECHABLE x 6 unidades - COCA COLA ZERO", price: 14850, category: "BEBIDAS", image: "catalogo/COCA_COLA_3LT_DESECHABLE_x_6_unidades_-_COCA_COLA_ZERO.webp" },
  { id: 'AND3DES-03', name: "COCA COLA 3LT DESECHABLE x 6 unidades - FANTA", price: 14850, category: "BEBIDAS", image: "catalogo/COCA_COLA_3LT_DESECHABLE_x_6_unidades_-_FANTA.webp" },
  { id: 'AND3DES-04', name: "COCA COLA 3LT DESECHABLE x 6 unidades - SPRITE", price: 14850, category: "BEBIDAS", image: "catalogo/COCA_COLA_3LT_DESECHABLE_x_6_unidades_-_SPRITE.jpg" },
  { id: 'AND3DES-05', name: "COCA COLA 3LT DESECHABLE x 6 unidades - INCA COLA", price: 14850, category: "BEBIDAS", image: "catalogo/COCA_COLA_3LT_DESECHABLE_x_6_unidades_-_INCA_COLA.jpg" },
  { id: 'AND3_MIX', name: "JABA COCA COLA 3LT RETORNABLE x 6 unidades", price: 12642, category: "RETORNABLE", image: "catalogo/JABA_COCA_COLA_3LT_RETORNABLE_x_6_unidades.jpg", isCustom: true },
  { id: 'AND591-01', name: "COCA COLA 591ML DESECHABLE x 6 unidades - COCA COLA", price: 5760, category: "BEBIDAS", image: "catalogo/COCA_COLA_591ML_DESECHABLE_x_6_unidades_-_COCA_COLA.jpg" },
  { id: 'AND591-02', name: "COCA COLA 591ML DESECHABLE x 6 unidades - COCA COLA ZERO", price: 5760, category: "BEBIDAS", image: "catalogo/COCA_COLA_591ML_DESECHABLE_x_6_unidades_-_COCA_COLA_ZERO.avif" },
  { id: 'AND591-03', name: "COCA COLA 591ML DESECHABLE x 6 unidades - FANTA", price: 5760, category: "BEBIDAS", image: "catalogo/COCA_COLA_591ML_DESECHABLE_x_6_unidades_-_FANTA.webp" },
  { id: 'AND591-04', name: "COCA COLA 591ML DESECHABLE x 6 unidades - SPRITE", price: 5760, category: "BEBIDAS", image: "catalogo/COCA_COLA_591ML_DESECHABLE_x_6_unidades_-_SPRITE.png" },
  { id: 'LATAC-01', name: "COCA COLA LATA 350 ML x 6 unidades - COCA COLA", price: 4428, category: "BEBIDAS", image: "catalogo/COCA_COLA_LATA_350_ML_x_6_unidades_-_COCA_COLA.webp" },
  { id: 'LATAC-02', name: "COCA COLA LATA 350 ML x 6 unidades - COCA COLA ZERO", price: 4428, category: "BEBIDAS", image: "catalogo/COCA_COLA_LATA_350_ML_x_6_unidades_-_COCA_COLA_ZERO.jpg" },
  { id: 'LATAC-03', name: "COCA COLA LATA 350 ML x 6 unidades - FANTA", price: 4428, category: "BEBIDAS", image: "catalogo/COCA_COLA_LATA_350_ML_x_6_unidades_-_FANTA.jpg" },
  { id: 'LATAC-04', name: "COCA COLA LATA 350 ML x 6 unidades - SPRITE", price: 4428, category: "BEBIDAS", image: "catalogo/COCA_COLA_LATA_350_ML_x_6_unidades_-_SPRITE.jpg" },
  { id: 'LATAC-05', name: "COCA COLA LATA 350 ML x 6 unidades - INCA COLA", price: 4428, category: "BEBIDAS", image: "catalogo/COCA_COLA_LATA_350_ML_x_6_unidades_-_INCA_COLA.webp" },
  { id: 'ICE275-01', name: "COCTEL CAPEL ICE 275 ML X 24 - SANDIA", price: 19000, category: "LICORES", image: "catalogo/COCTEL_CAPEL_ICE_275_ML_X_24_-_SANDIA.webp" },
  { id: 'ICE275-02', name: "COCTEL CAPEL ICE 275 ML X 24 - MOJITO", price: 19000, category: "LICORES", image: "catalogo/COCTEL_CAPEL_ICE_275_ML_X_24_-_MOJITO.webp" },
  { id: 'ICE275-03', name: "COCTEL CAPEL ICE 275 ML X 24 - BERRIE", price: 19000, category: "LICORES", image: "catalogo/COCTEL_CAPEL_ICE_275_ML_X_24_-_BERRIE.webp" },
  { id: 'ICE275-04', name: "COCTEL CAPEL ICE 275 ML X 24 - MANZANA", price: 19000, category: "LICORES", image: "catalogo/COCTEL_CAPEL_ICE_275_ML_X_24_-_MANZANA.webp" },
  { id: 'COR330', name: "CORONA 330ML X18 UNID", price: 14850, category: "CERVEZA", image: "catalogo/COR330.webp" },
  { id: 'COR620', name: "CORONA 620CC X12 UNID", price: 13090, category: "CERVEZA", image: "catalogo/CORONA_620CC_X12_UNID.avif" },
  { id: 'CRISLT', name: "CRISTAL LATA 470CC x 24 unidades", price: 16560, category: "CERVEZA", image: "catalogo/CRISTAL_LATA_470CC_x_24_unidades.webp" },
  { id: 'CRIS12', name: "CRISTAL LATA 470cc X12UNID", price: 8520, category: "CERVEZA", image: "catalogo/CRIS12.webp" },
  { id: 'LIN', name: "ENCENDEDOR LIN", price: 2100, category: "BEBIDAS", image: "catalogo/LIN.webp" },
  { id: 'ZO-01', name: "ENERGY ZOOM 473 ML x 24 unidades - ZOOM PURPLE", price: 15600, category: "ENERGÃ‰TICAS", image: "catalogo/ENERGY_ZOOM_473ML_x_12_unidades_-_PURPLE.webp" },
  { id: 'ZO-02', name: "ENERGY ZOOM 473 ML x 24 unidades - ZOOM WHITE", price: 15600, category: "ENERGÃ‰TICAS", image: "catalogo/ENERGY_ZOOM_473ML_x_12_unidades_-_WHITE.jpg" },
  { id: 'ESPAMAR', name: "ESPUMANTE AMARANTA BRUT 12.4g 750", price: 4650, category: "LICORES", image: "catalogo/ESPAMAR.webp" },
  { id: 'ESPCARM', name: "ESPUMANTE CARMEN FK MOSCATO 12g 250", price: 20262, category: "LICORES", image: "catalogo/ESPCARM.webp" },
  { id: 'EXP500', name: "EXPORTACION VINO 500ML", price: 14768, category: "BEBIDAS", image: "catalogo/EXP500.webp" },
  { id: 'EXPRB_MIX', name: "JABA EXPRESS CCU X30", price: 11200, category: "RETORNABLE", image: "catalogo/JABA_EXPRESS_CCU_X30.png", isCustom: true },
  { id: 'SXF-01', name: "FASTYLE 630ML X 6UNID - TROPICAL BLUE", price: 7900, category: "BEBIDAS", image: "catalogo/SXF.webp" },
  { id: 'SXF-02', name: "FASTYLE 630ML X 6UNID - FRUTILLA", price: 7900, category: "BEBIDAS", image: "catalogo/SXF.webp" },
  { id: 'SXF-03', name: "FASTYLE 630ML X 6UNID - FRUTILLA KIWI", price: 7900, category: "BEBIDAS", image: "catalogo/SXF.webp" },
  { id: 'FR2-01', name: "Fruna 2.0 LT x 6 unidades - COLA", price: 3490, category: "BEBIDAS", image: "catalogo/Fruna_2.0_LT_x_6_unidades_-_PINA.webp" },
  { id: 'FR2-02', name: "Fruna 2.0 LT x 6 unidades - PIÑA", price: 3490, category: "BEBIDAS", image: "catalogo/Fruna_2.0_LT_x_6_unidades_-_PINA.webp" },
  { id: 'FR2-03', name: "Fruna 2.0 LT x 6 unidades - PAPAYA", price: 3490, category: "BEBIDAS", image: "catalogo/Fruna_2.0_LT_x_6_unidades_-_PAPAYA.webp" },
  { id: 'FR2-04', name: "Fruna 2.0 LT x 6 unidades - NARANJA", price: 3490, category: "BEBIDAS", image: "catalogo/Fruna_2.0_LT_x_6_unidades_-_NARANJA.webp" },
  { id: 'FR2-05', name: "Fruna 2.0 LT x 6 unidades - LIMON SODA", price: 3490, category: "BEBIDAS", image: "catalogo/Fruna_2.0_LT_x_6_unidades_-_LIMON_SODA.webp" },
  { id: 'FR2-06', name: "Fruna 2.0 LT x 6 unidades - FRUTAL", price: 3490, category: "BEBIDAS", image: "catalogo/Fruna_2.0_LT_x_6_unidades_-_FRUTAL.webp" },
  { id: 'FR2-07', name: "Fruna 2.0 LT x 6 unidades - GINGER ALE", price: 3490, category: "BEBIDAS", image: "catalogo/Fruna_2.0_LT_x_6_unidades_-_GINGER_ALE.webp" },
  { id: 'FR500-01', name: "Fruna 500ml x 12 unidades - COLA", price: 3590, category: "BEBIDAS", image: "catalogo/Fruna_500ml_x_12_unidades_-_COLA.png" },
  { id: 'FR500-02', name: "Fruna 500ml x 12 unidades - PIÑA", price: 3590, category: "BEBIDAS", image: "catalogo/Fruna_500ml_x_12_unidades_-_PINA.jpg" },
  { id: 'FR500-03', name: "Fruna 500ml x 12 unidades - PAPAYA", price: 3590, category: "BEBIDAS", image: "catalogo/Fruna_500ml_x_12_unidades_-_PAPAYA.webp" },
  { id: 'FR500-04', name: "Fruna 500ml x 12 unidades - NARANJA", price: 3590, category: "BEBIDAS", image: "catalogo/Fruna_500ml_x_12_unidades_-_NARANJA.webp" },
  { id: 'FR500-05', name: "Fruna 500ml x 12 unidades - LIMON SODA", price: 3590, category: "BEBIDAS", image: "catalogo/Fruna_500ml_x_12_unidades_-_LIMON_SODA.jpg" },
  { id: 'FR500-06', name: "Fruna 500ml x 12 unidades - FRUTAL", price: 3590, category: "BEBIDAS", image: "catalogo/Fruna_500ml_x_12_unidades_-_FRUTAL.jpg" },
  { id: 'FR500-07', name: "Fruna 500ml x 12 unidades - GINGER ALE", price: 3590, category: "BEBIDAS", image: "catalogo/Fruna_500ml_x_12_unidades_-_GINGER_ALE.webp" },
  { id: 'GATO1A-01', name: "GATORADE 1LT DESECHABLE x 6 unidades - AZUL", price: 7260, category: "BEBIDAS", image: "catalogo/GATORADE_1LT_DESECHABLE_x_6_unidades_-_AZUL.avif" },
  { id: 'GATO1A-02', name: "GATORADE 1LT DESECHABLE x 6 unidades - ROJO", price: 7260, category: "BEBIDAS", image: "catalogo/GATORADE_1LT_DESECHABLE_x_6_unidades_-_ROJO.jpg" },
  { id: 'GATO1A-03', name: "GATORADE 1LT DESECHABLE x 6 unidades - NARANJA", price: 7260, category: "BEBIDAS", image: "catalogo/GATORADE_1LT_DESECHABLE_x_6_unidades_-_NARANJA.jpg" },
  { id: 'GATO750-01', name: "GATORADE 750ML x 6 unidades - AZUL", price: 5280, category: "BEBIDAS", image: "catalogo/GATORADE_750ML_x_6_unidades_-_AZUL.jpg" },
  { id: 'GATO750-02', name: "GATORADE 750ML x 6 unidades - ROJO", price: 5280, category: "BEBIDAS", image: "catalogo/GATORADE_750ML_x_6_unidades_-_ROJO.webp" },
  { id: 'GATO750-03', name: "GATORADE 750ML x 6 unidades - NARANJA", price: 5280, category: "BEBIDAS", image: "catalogo/GATORADE_750ML_x_6_unidades_-_NARANJA.webp" },
  { id: 'GINGORD', name: "GIN GORDONS 750 cc", price: 11650, category: "GIN", image: "catalogo/GINGORD.webp" },
  { id: 'TQRAYBOS', name: "GIN TANQUERAY BOSSA NOVA 700cc", price: 16920, category: "GIN", image: "catalogo/TQRAYBOS.webp" },
  { id: 'TQRAYLOND', name: "GIN TANQUERAY LON D 700CC", price: 15690, category: "GIN", image: "catalogo/TQRAYLOND.webp" },
  { id: 'TQRAYROY', name: "GIN TANQUERAY ROYALE 700cc", price: 16920, category: "GIN", image: "catalogo/TQRAYROY.webp" },
  { id: 'TQRAYSEVI', name: "GIN TANQUERAY SEVI 700 cc", price: 16920, category: "GIN", image: "catalogo/TQRAYSEVI.webp" },
  { id: 'H1', name: "HUEVO 1ERA", price: 32000, category: "BEBIDAS", image: "catalogo/H1.webp" },
  { id: 'HEX', name: "HUEVO EXTRA", price: 36000, category: "BEBIDAS", image: "catalogo/HEX.webp" },
  { id: 'IRON-01', name: "ISOTONICA IRONADE 1LT - ROJO", price: 4500, category: "LICORES", image: "catalogo/IRON.webp" },
  { id: 'IRON-02', name: "ISOTONICA IRONADE 1LT - AZUL", price: 4500, category: "LICORES", image: "catalogo/IRON.webp" },
  { id: 'IRON-03', name: "ISOTONICA IRONADE 1LT - NARANJA", price: 4500, category: "LICORES", image: "catalogo/IRON.webp" },
  { id: 'JABAMIX', name: "JABA MIXTA 10 BEBIDAS", price: 10250, category: "PROMOCIONES", image: "catalogo/JABAMIX.webp" },
  { id: 'JAL-01', name: "JUGO ANDINA 340ML X 6UNID - DURAZNO", price: 3900, category: "BEBIDAS", image: "catalogo/JUGO_ANDINA_340ML_X_6UNID_-_DURAZNO.webp" },
  { id: 'JAL-02', name: "JUGO ANDINA 340ML X 6UNID - PERA", price: 3900, category: "BEBIDAS", image: "catalogo/JUGO_ANDINA_340ML_X_6UNID_-_PERA.webp" },
  { id: 'JC2-01', name: "JUGO CYRO 2LT x 6 unidades - PIÑA", price: 4250, category: "BEBIDAS", image: "catalogo/Fruna_2.0_LT_x_6_unidades_-_PINA.webp" },
  { id: 'JC2-02', name: "JUGO CYRO 2LT x 6 unidades - NARANJA", price: 4250, category: "BEBIDAS", image: "catalogo/GATORADE_750ML_x_6_unidades_-_NARANJA.webp" },
  { id: 'JC2-03', name: "JUGO CYRO 2LT x 6 unidades - FRUTILLA", price: 4250, category: "BEBIDAS", image: "catalogo/JC2.webp" },
  { id: 'JC2-04', name: "JUGO CYRO 2LT x 6 unidades - DURAZNO", price: 4250, category: "BEBIDAS", image: "catalogo/JUGO_ANDINA_340ML_X_6UNID_-_DURAZNO.webp" },
  { id: 'JUMEXM-01', name: "JUMEX 355 X BANDEJA x 24 unidades - PIÑA", price: 15650, category: "BEBIDAS", image: "catalogo/JUMEXM.webp" },
  { id: 'JUMEXM-02', name: "JUMEX 355 X BANDEJA x 24 unidades - PIÑA COCO", price: 15650, category: "BEBIDAS", image: "catalogo/JUMEXM.webp" },
  { id: 'JUMEXM-03', name: "JUMEX 355 X BANDEJA x 24 unidades - MANGO", price: 15650, category: "BEBIDAS", image: "catalogo/SCORE_473ML_x_24_unidades_-_MANGO.avif" },
  { id: 'JUMEXM-04', name: "JUMEX 355 X BANDEJA x 24 unidades - DURAZNO", price: 15650, category: "BEBIDAS", image: "catalogo/JUMEXM.webp" },
  { id: 'JUMEXM-05', name: "JUMEX 355 X BANDEJA x 24 unidades - PERA", price: 15650, category: "BEBIDAS", image: "catalogo/JUMEXM.webp" },
  { id: 'JUMEXM-06', name: "JUMEX 355 X BANDEJA x 24 unidades - MANZANA", price: 15650, category: "BEBIDAS", image: "catalogo/JUMEXM.webp" },
  { id: 'KAPOF-01', name: "KAPO X24 UNID - PIÑA", price: 5800, category: "BEBIDAS", image: "catalogo/KAPO_X24_UNID_-_PINA.webp" },
  { id: 'KAPOF-02', name: "KAPO X24 UNID - MANZANA", price: 5800, category: "BEBIDAS", image: "catalogo/KAPO_X24_UNID_-_MANZANA.webp" },
  { id: 'KAPOF-03', name: "KAPO X24 UNID - FRAMBUESA", price: 5800, category: "BEBIDAS", image: "catalogo/KAPO_X24_UNID_-_FRAMBUESA.webp" },
  { id: 'KAPOF-04', name: "KAPO X24 UNID - NARANJA", price: 5800, category: "BEBIDAS", image: "catalogo/KAPO_X24_UNID_-_NARANJA.png" },
  { id: 'LATAK6-01', name: "LATA CCU X 6 UNIDAD. - ´PAP", price: 3780, category: "BEBIDAS", image: "catalogo/LATA_CCU_X_6_UNIDAD._-_´PAP.jpg" },
  { id: 'LATAK6-02', name: "LATA CCU X 6 UNIDAD. - BILZ", price: 3780, category: "BEBIDAS", image: "catalogo/LATA_CCU_X_6_UNIDAD._-_BILZ.jpg" },
  { id: 'LATAK6-03', name: "LATA CCU X 6 UNIDAD. - KEM", price: 3780, category: "BEBIDAS", image: "catalogo/LATA_CCU_X_6_UNIDAD._-_KEM.webp" },
  { id: 'LATAK6-04', name: "LATA CCU X 6 UNIDAD. - LIMON", price: 3780, category: "BEBIDAS", image: "catalogo/LATA_CCU_X_6_UNIDAD._-_LIMON.jpg" },
  { id: 'LATAK6-05', name: "LATA CCU X 6 UNIDAD. - PEPSI", price: 3780, category: "BEBIDAS", image: "catalogo/LATA_CCU_X_6_UNIDAD._-_PEPSI.webp" },
  { id: 'LATAK6-06', name: "LATA CCU X 6 UNIDAD. - PEPSI ZERO", price: 3780, category: "BEBIDAS", image: "catalogo/LATA_CCU_X_6_UNIDAD._-_PEPSI_ZERO.webp" },
  { id: 'LATAK6-07', name: "LATA CCU X 6 UNIDAD. - GINGER", price: 3780, category: "BEBIDAS", image: "catalogo/LATA_CCU_X_6_UNIDAD._-_GINGER.webp" },
  { id: 'LATAK6-08', name: "LATA CCU X 6 UNIDAD. - CRUSH", price: 3780, category: "BEBIDAS", image: "catalogo/LATA_CCU_X_6_UNIDAD._-_CRUSH.webp" },
  { id: 'LATAK6-09', name: "LATA CCU X 6 UNIDAD. - SEVEN UP", price: 3780, category: "BEBIDAS", image: "catalogo/LATA_CCU_X_6_UNIDAD._-_SEVEN_UP.webp" },
  { id: 'LATAK6-10', name: "LATA CCU X 6 UNIDAD. - KEM EXTREME", price: 3780, category: "BEBIDAS", image: "catalogo/LATA_CCU_X_6_UNIDAD._-_KEM_EXTREME.jpg" },
  { id: 'ESC710', name: "LATA ESCUDO 710ML X 24 UNID", price: 18960, category: "CERVEZA", image: "catalogo/LATA_ESCUDO_710ML_X_24_UNID.png" },
  { id: 'MINIC-01', name: "LATA MINI 200ML 6 UNIDAD - COCA COLA", price: 3330, category: "BEBIDAS", image: "catalogo/LATA_MINI_200ML_6_UNIDAD_-_COCA_COLA.webp" },
  { id: 'MINIC-02', name: "LATA MINI 200ML 6 UNIDAD - COCA COLA ZERO", price: 3330, category: "BEBIDAS", image: "catalogo/LATA_MINI_200ML_6_UNIDAD_-_COCA_COLA_ZERO.jfif" },
  { id: 'MINIC-03', name: "LATA MINI 200ML 6 UNIDAD - FANTA", price: 3330, category: "BEBIDAS", image: "catalogo/LATA_MINI_200ML_6_UNIDAD_-_FANTA.jpg" },
  { id: 'MINIC-04', name: "LATA MINI 200ML 6 UNIDAD - SPRITE", price: 3330, category: "BEBIDAS", image: "catalogo/LATA_MINI_200ML_6_UNIDAD_-_SPRITE.webp" },
  { id: 'MAL355', name: "MALTIN 355 ML X 24 UNIDAD", price: 27600, category: "BEBIDAS", image: "catalogo/MAL355.webp" },
  { id: 'MONSO6-01', name: "MONSTER 473ML X6 UNID. - MANGO LOCO", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSTER_473ML_X6_UNID._-_MANGO_LOCO.webp" },
  { id: 'MONSO6-02', name: "MONSTER 473ML X6 UNID. - PIPERLINE PUNSH", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSTER_473ML_X6_UNID._-_PIPERLINE_PUNSH.webp" },
  { id: 'MONSO6-03', name: "MONSTER 473ML X6 UNID. - ZERO ULTRA", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSTER_473ML_X6_UNID._-_ZERO_ULTRA.jpg" },
  { id: 'MONSO6-04', name: "MONSTER 473ML X6 UNID. - ULTRA PARADISE", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSTER_473ML_X6_UNID._-_ULTRA_PARADISE.webp" },
  { id: 'MONSO6-05', name: "MONSTER 473ML X6 UNID. - ORIGINAL", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSTER_473ML_X6_UNID._-_ORIGINAL.webp" },
  { id: 'MONSO6-06', name: "MONSTER 473ML X6 UNID. - ORIGINAL ZERO", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSTER_473ML_X6_UNID._-_ORIGINAL_ZERO.webp" },
  { id: 'MONSO6-07', name: "MONSTER 473ML X6 UNID. - RIPPER", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo/MONSTER_473ML_X6_UNID._-_RIPPER.webp" },
  { id: 'PISAL', name: "PISCO ALTO DEL CARMEN 1LT", price: 6400, category: "PISCO", image: "catalogo/PISAL.webp" },
  { id: 'POWA1-01', name: "POWERADE 1.1LT x 6 unidades - AZUL", price: 7550, category: "BEBIDAS", image: "catalogo/POWERADE_850ML_x_6_unidades_-_AZUL.jpg" },
  { id: 'POWA1-02', name: "POWERADE 1.1LT x 6 unidades - ROJO", price: 7550, category: "BEBIDAS", image: "catalogo/POWERADE_850ML_x_6_unidades_-_ROJO.webp" },
  { id: 'POWA1-03', name: "POWERADE 1.1LT x 6 unidades - NARANJA", price: 7550, category: "BEBIDAS", image: "catalogo/GATORADE_1LT_DESECHABLE_x_6_unidades_-_NARANJA.jpg" },
  { id: 'PROD002', name: "Pack Cerveza Heineken Lata 6x350cc", price: 4990, category: "CERVEZA", image: "catalogo/Pack_Cerveza_Heineken_Lata_6x350cc.webp" },
  { id: 'PROD006', name: "Papas Fritas Kryzpo Original 130g", price: 1490, category: "LICORES", image: "catalogo/Papas_Fritas_Kryzpo_Original_130g.webp" },
  { id: 'PROD001', name: "Pisco Mistral 35° 1L", price: 6990, category: "LICORES", image: "catalogo/Pisco_Mistral_35_1L.webp" },
  { id: 'RB355', name: "RED BULL 355CC X 12 UNIDADES", price: 20760, category: "ENERGÃ‰TICAS", image: "catalogo/RED_BULL_355CC_X_12_UNIDADES.jpg" },
  { id: 'RB473', name: "RED BULL 473CC X 12 UNIDADES", price: 25920, category: "ENERGÃ‰TICAS", image: "catalogo/RED_BULL_473CC_X_12_UNIDADES.webp" },
  { id: 'RB250', name: "REDBULL 250ML x12 unid", price: 15200, category: "BEBIDAS", image: "catalogo/REDBULL_250ML_x12_unid.avif" },
  { id: 'RSTAR-01', name: "ROCKSTAR 500 ML x 12 unidades - ORIGINAL", price: 11160, category: "BEBIDAS", image: "catalogo/ROCKSTAR_500_ML_x_12_unidades_-_MANGO_POWER.webp" },
  { id: 'RSTAR-02', name: "ROCKSTAR 500 ML x 12 unidades - MANGO POWER", price: 11160, category: "BEBIDAS", image: "catalogo/ROCKSTAR_500_ML_x_12_unidades_-_MANGO_POWER.webp" },
  { id: 'RSTAR-03', name: "ROCKSTAR 500 ML x 12 unidades - SANDIA PUNSH", price: 11160, category: "BEBIDAS", image: "catalogo/ROCKSTAR_500_ML_x_12_unidades_-_SANDIA_PUNSH.jpeg" },
  { id: 'RONANEJ', name: "RON MADDERO ANEJO 750 cc", price: 6250, category: "RON", image: "catalogo/RONANEJ.webp" },
  { id: 'RONBL', name: "RON MADDERO BLANCO 750 cc", price: 4550, category: "RON", image: "catalogo/RONBL.webp" },
  { id: 'RONDOR1', name: "RON MADDERO DORADO 1LT", price: 5190, category: "RON", image: "catalogo/RONDOR1.webp" },
  { id: 'RONANE', name: "RON MADDERO DORADO 750 cc", price: 4990, category: "RON", image: "catalogo/RONANE.webp" },
  { id: 'ROY470', name: "ROYAL 470 X 24 UNID", price: 18960, category: "CERVEZA", image: "catalogo/ROYAL_470_X_24_UNID.webp" },
  { id: 'SCOREG-01', name: "SCORE 473ML x 24 unidades - GORILLA", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_473ML_x_24_unidades_-_GORILLA.webp" },
  { id: 'SCOREG-02', name: "SCORE 473ML x 24 unidades - FRUIT PUNSH", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_473ML_x_24_unidades_-_FRUIT_PUNSH.avif" },
  { id: 'SCOREG-03', name: "SCORE 473ML x 24 unidades - MANGO", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_473ML_x_24_unidades_-_MANGO.avif" },
  { id: 'SCOREG-04', name: "SCORE 473ML x 24 unidades - MOJITO", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_473ML_x_24_unidades_-_MOJITO.webp" },
  { id: 'SCOREG-05', name: "SCORE 473ML x 24 unidades - BUBLE GUM", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_473ML_x_24_unidades_-_BUBLE_GUM.webp" },
  { id: 'SCOREG-06', name: "SCORE 473ML x 24 unidades - ORIGINAL", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_473ML_x_24_unidades_-_ORIGINAL.webp" },
  { id: 'SCOREG-07', name: "SCORE 473ML x 24 unidades - WATER MELON", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_473ML_x_24_unidades_-_WATER_MELON.jpeg" },
  { id: 'SCOREG-08', name: "SCORE 473ML x 24 unidades - RADICAL WHILE", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_473ML_x_24_unidades_-_RADICAL_WHILE.webp" },
  { id: 'ENER250-01', name: "SCORE ENERGY DRINK 250 ML x 16 unidades - ORIGINAL", price: 13000, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_ENERGY_DRINK_250_ML_x_16_unidades_-_ORIGINAL.webp" },
  { id: 'ENER250-02', name: "SCORE ENERGY DRINK 250 ML x 16 unidades - SANDIA", price: 13000, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_ENERGY_DRINK_250_ML_x_16_unidades_-_ORIGINAL.webp" },
  { id: 'ENER250-03', name: "SCORE ENERGY DRINK 250 ML x 16 unidades - FRUTOS TROPICALES", price: 13000, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_ENERGY_DRINK_250_ML_x_16_unidades_-_ORIGINAL.webp" },
  { id: 'ENERGY-01', name: "SCORE ENERGY DRINK 500 ML x 24 unidades - ORIGINAL", price: 18000, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_ENERGY_DRINK_500_ML_x_24_unidades_-_ORIGINAL.webp" },
  { id: 'ENERGY-02', name: "SCORE ENERGY DRINK 500 ML x 24 unidades - SANDIA", price: 18000, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_ENERGY_DRINK_500_ML_x_24_unidades_-_ORIGINAL.webp" },
  { id: 'ENERGY-03', name: "SCORE ENERGY DRINK 500 ML x 24 unidades - FRUTOS TROPICALES", price: 18000, category: "ENERGÃ‰TICAS", image: "catalogo/SCORE_ENERGY_DRINK_500_ML_x_24_unidades_-_ORIGINAL.webp" },
  { id: 'SOL650', name: "SOL 650 x 12 unidades", price: 12000, category: "CERVEZA", image: "catalogo/SOL_650_x_12_unidades.jpg" },
  { id: 'SOPA-01', name: "SOPA MOLINOVA 94G X CAJA DE 9 unidades - POLLO", price: 9000, category: "BEBIDAS", image: "catalogo/SOPA.webp" },
  { id: 'SOPA-02', name: "SOPA MOLINOVA 94G X CAJA DE 9 unidades - CARNE", price: 9000, category: "BEBIDAS", image: "catalogo/SOPA.webp" },
  { id: 'SOPA-03', name: "SOPA MOLINOVA 94G X CAJA DE 9 unidades - CARNE PICANTE", price: 9000, category: "BEBIDAS", image: "catalogo/SOPA.webp" },
  { id: 'SOPA-04', name: "SOPA MOLINOVA 94G X CAJA DE 9 unidades - CAMARON", price: 9000, category: "BEBIDAS", image: "catalogo/SOPA.webp" },
  { id: 'AND125DES', name: "SPRITE 1.25 DESECHABLE x 6 unidades", price: 5340, category: "BEBIDAS", image: "catalogo/SPRITE_1.25_DESECHABLE_x_6_unidades.webp" },
  { id: 'SX', name: "SUEROX 630ML SURTIDO", price: 17880, category: "BEBIDAS", image: "catalogo/SX.webp" },
  { id: 'LIPT15-01', name: "TE LIPTON 1.5 LT DESECHABLE x 6 unidades - LIMON", price: 11526, category: "BEBIDAS", image: "catalogo/TE_LIPTON_1.5_LT_DESECHABLE_x_6_unidades_-_LIMON.webp" },
  { id: 'LIPT15-02', name: "TE LIPTON 1.5 LT DESECHABLE x 6 unidades - DURAZNO", price: 11526, category: "BEBIDAS", image: "catalogo/TE_LIPTON_1.5_LT_DESECHABLE_x_6_unidades_-_DURAZNO.webp" },
  { id: 'LIPT15-03', name: "TE LIPTON 1.5 LT DESECHABLE x 6 unidades - FRAMBUESA", price: 11526, category: "BEBIDAS", image: "catalogo/TE_LIPTON_1.5_LT_DESECHABLE_x_6_unidades_-_FRAMBUESA.avif" },
  { id: 'LIPT15-04', name: "TE LIPTON 1.5 LT DESECHABLE x 6 unidades - TE VERDE MANGO", price: 11526, category: "BEBIDAS", image: "catalogo/TE_LIPTON_1.5_LT_DESECHABLE_x_6_unidades_-_TE_VERDE_MANGO.webp" },
  { id: 'LIPT15-05', name: "TE LIPTON 1.5 LT DESECHABLE x 6 unidades - TE VERDE LIMON", price: 11526, category: "BEBIDAS", image: "catalogo/TE_LIPTON_1.5_LT_DESECHABLE_x_6_unidades_-_TE_VERDE_LIMON.webp" },
  { id: 'VIN120M', name: "VINO 120 1.5 LT X6 UNID", price: 18624, category: "BEBIDAS", image: "catalogo/VIN120M.webp" },
  { id: 'VINMED', name: "VINO 120 3 MEDLLA L.HARVEST 12g 750 X3 UNID", price: 12800, category: "BEBIDAS", image: "catalogo/VINMED.webp" },
  { id: 'VMREAL', name: "VINO CARM FK/MREAL CS 13.5g 750 X 3 UNID", price: 12680, category: "BEBIDAS", image: "catalogo/VMREAL.webp" },
  { id: 'VINCAR', name: "VINO FLORESTA CAR 13.3g 750cc", price: 15800, category: "BEBIDAS", image: "catalogo/VINCAR.webp" },
  { id: 'VINCHARDONNAY', name: "VINO FLORESTA CHARDONNAY 13.4g 750CC", price: 16200, category: "BEBIDAS", image: "catalogo/VINCHARDONNAY.webp" },
  { id: 'VINREAL', name: "VINO M. REAL RVA X2 CS-MER 13.5G 750CC", price: 7170, category: "BEBIDAS", image: "catalogo/VINREAL.webp" },
  { id: 'VITSG16-01', name: "VITAL 1.6LT - CON GAS", price: 4866, category: "AGUA", image: "catalogo/VITSG16.webp" },
  { id: 'VITSG16-02', name: "VITAL 1.6LT - SIN GAS", price: 4866, category: "AGUA", image: "catalogo/VITSG16.webp" },
  { id: 'VITP', name: "VITAL 1LT x 6 unidades", price: 8280, category: "AGUA", image: "catalogo/GATORADE_1LT_DESECHABLE_x_6_unidades_-_AZUL.avif" },
  { id: 'VIT330-01', name: "VITAL 330 ML VIDRIO X 12UNID. - CON GAS", price: 8280, category: "AGUA", image: "catalogo/VIT330.webp" },
  { id: 'VIT330-02', name: "VITAL 330 ML VIDRIO X 12UNID. - SIN GAS", price: 8280, category: "AGUA", image: "catalogo/VIT330.webp" },
  { id: 'VITSG600-01', name: "VITAL 600ML x 12 unidades - CON GAS", price: 5940, category: "AGUA", image: "catalogo/CACHANTUN_500ML_x_12_unidades_-_STRONG_GAS.avif" },
  { id: 'VITSG600-02', name: "VITAL 600ML x 12 unidades - SIN GAS", price: 5940, category: "AGUA", image: "catalogo/CACHANTUN_500ML_x_12_unidades_-_STRONG_GAS.avif" },
  { id: 'PROD003', name: "Vino Casillero del Diablo Cabernet Sauvignon 750cc", price: 4490, category: "BEBIDAS", image: "catalogo/Vino_Casillero_del_Diablo_Cabernet_Sauvignon_750cc.png" },
  { id: 'WATTSD-01', name: "WATTS 1.5LT DESECHABLE x 6 unidades - DURAZNO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_DURAZNO.png" },
  { id: 'WATTSD-02', name: "WATTS 1.5LT DESECHABLE x 6 unidades - NARANJA", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_NARANJA.jpg" },
  { id: 'WATTSD-03', name: "WATTS 1.5LT DESECHABLE x 6 unidades - PIÑA", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_PINA.jpg" },
  { id: 'WATTSD-04', name: "WATTS 1.5LT DESECHABLE x 6 unidades - DURAZNO CERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_DURAZNO_CERO.jpg" },
  { id: 'WATTSD-05', name: "WATTS 1.5LT DESECHABLE x 6 unidades - NARANJA ZERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_NARANJA_ZERO.webp" },
  { id: 'WATTSD-06', name: "WATTS 1.5LT DESECHABLE x 6 unidades - PIÑA ZERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_PINA_ZERO.webp" },
  { id: 'WATTSD-07', name: "WATTS 1.5LT DESECHABLE x 6 unidades - TUTIFRUTILLA ORIGINAL", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_TUTIFRUTILLA_ORIGINAL.webp" },
  { id: 'WATTSD-08', name: "WATTS 1.5LT DESECHABLE x 6 unidades - TUTIFRUTILLA ZERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_TUTIFRUTILLA_ZERO.webp" },
  { id: 'WATTSD-09', name: "WATTS 1.5LT DESECHABLE x 6 unidades - NARANJA MANZANA", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_NARANJA_MANZANA.webp" },
  { id: 'WATTSD-10', name: "WATTS 1.5LT DESECHABLE x 6 unidades - MANGO ZERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_MANGO_ZERO.webp" },
  { id: 'WATTSD-11', name: "WATTS 1.5LT DESECHABLE x 6 unidades - MARACUYA ZERO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_MARACUYA_ZERO.webp" },
  { id: 'WATTSD-12', name: "WATTS 1.5LT DESECHABLE x 6 unidades - NARANJA PLATANO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_NARANJA_PLATANO.webp" },
  { id: 'WATTSD-13', name: "WATTS 1.5LT DESECHABLE x 6 unidades - TUTIKIWI", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_TUTIKIWI.webp" },
  { id: 'WATTSD-14', name: "WATTS 1.5LT DESECHABLE x 6 unidades - TUTIARANDANO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_TUTIARANDANO.webp" },
  { id: 'WATTSD-15', name: "WATTS 1.5LT DESECHABLE x 6 unidades - DAMASCO", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_DAMASCO.webp" },
  { id: 'WATTSD-16', name: "WATTS 1.5LT DESECHABLE x 6 unidades - MANZANA", price: 9120, category: "BEBIDAS", image: "catalogo/WATTS_1.5LT_DESECHABLE_x_6_unidades_-_MANZANA.webp" },
  { id: 'WB300-01', name: "WATTS BOCA ANCHA 300 ML x 24 unidades - DURAZNO", price: 19920, category: "BEBIDAS", image: "catalogo/WATTS_BOCA_ANCHA_300_ML_x_24_unidades_-_DURAZNO.webp" },
  { id: 'WB300-02', name: "WATTS BOCA ANCHA 300 ML x 24 unidades - NARANJA", price: 19920, category: "BEBIDAS", image: "catalogo/WATTS_BOCA_ANCHA_300_ML_x_24_unidades_-_NARANJA.png" },
  { id: 'WB300-03', name: "WATTS BOCA ANCHA 300 ML x 24 unidades - PIÑA", price: 19920, category: "BEBIDAS", image: "catalogo/WATTS_BOCA_ANCHA_300_ML_x_24_unidades_-_NARANJA.png" },
  { id: 'WB300-04', name: "WATTS BOCA ANCHA 300 ML x 24 unidades - TUTIFRUTILLA", price: 19920, category: "BEBIDAS", image: "catalogo/WATTS_BOCA_ANCHA_300_ML_x_24_unidades_-_TUTIFRUTILLA.webp" },
  { id: 'WHISBUCH', name: "WHISKY BUCHANANS DELUXE 750 CC", price: 24230, category: "WHISKY", image: "catalogo/WHISBUCH.webp" },
  { id: 'WHISKEY', name: "WHISKY JACK DANIEL 50ML", price: 2600, category: "WHISKY", image: "catalogo/WHISKEY.webp" },
  { id: 'WHISBLACK', name: "WHISKY JW BLACK 750 ml - BLACK 200ML", price: 28990, category: "WHISKY", image: "catalogo/WHISBLACK.webp" },
  { id: 'WHISGOLD', name: "WHISKY JW GOLD LABEL 750 ml - Copa", price: 56000, category: "WHISKY", image: "catalogo/WHISGOLD.webp" },
  { id: 'WHISRED', name: "WHISKY RED LABEL 750 CC", price: 9990, category: "WHISKY", image: "catalogo/WHISRED.webp" },
  { id: 'WHISSAND', name: "WHISKY SANDY MAC 1LT", price: 12500, category: "WHISKY", image: "catalogo/WHISSAND.webp" },
  { id: 'WHISHOR', name: "WHISKY WHITE HOR 750 cc 40G X1", price: 7396, category: "WHISKY", image: "catalogo/WHISHOR.webp" },
  { id: 'BIGCOLA473', name: "BIG COLA LATA 473ML x 6 unidades", price: 3180, category: "BEBIDAS", image: "catalogo/BIG_COLA_LATA_473ML_x_6_unidades.webp" },
  { id: 'BIGUVA17', name: "BIG UVA 1.7L x 6 unidades", price: 5250, category: "BEBIDAS", image: "catalogo/BIG_UVA_1.7L_x_6_unidades.webp" },
  { id: 'ALOE15-01', name: "ALOE VERA 1.5L x 12 unidades - ORIGINAL", price: 20280, category: "BEBIDAS", image: "catalogo/ALOE_VERA_1.5L_x_12_unidades_-_ORIGINAL.webp" },
  { id: 'ALOE15-02', name: "ALOE VERA 1.5L x 12 unidades - PIÑA", price: 20280, category: "BEBIDAS", image: "catalogo/ALOE_VERA_1.5L_x_12_unidades_-_PINA.webp" },
  { id: 'ALOE15-03', name: "ALOE VERA 1.5L x 12 unidades - FRUTILLA", price: 20280, category: "BEBIDAS", image: "catalogo/ALOE_VERA_1.5L_x_12_unidades_-_FRUTILLA.png" },
  { id: 'SCOREW473-01', name: "SCORE WATER 473ML x 24 unidades - ALOE VERA", price: 18000, category: "ENERGÉTICAS", image: "catalogo/SCORE_WATER_473ML_x_24_unidades_-_ALOE_VERA.webp" },
  { id: 'SCOREW473-02', name: "SCORE WATER 473ML x 24 unidades - SIN GAS", price: 18000, category: "ENERGÉTICAS", image: "catalogo/SCORE_WATER_473ML_x_24_unidades_-_SIN_GAS.jpg" },
  { id: 'SCOREW473-03', name: "SCORE WATER 473ML x 24 unidades - CON GAS", price: 18000, category: "ENERGÉTICAS", image: "catalogo/SCORE_WATER_473ML_x_24_unidades_-_CON_GAS.jpg" },
  { id: 'ZOOM12-01', name: "ENERGY ZOOM 473ML x 12 unidades - WHITE", price: 7800, category: "ENERGÉTICAS", image: "catalogo/ENERGY_ZOOM_473ML_x_12_unidades_-_WHITE.jpg" },
  { id: 'ZOOM12-02', name: "ENERGY ZOOM 473ML x 12 unidades - PURPLE", price: 7800, category: "ENERGÉTICAS", image: "catalogo/ENERGY_ZOOM_473ML_x_12_unidades_-_PURPLE.webp" },
  { id: 'EXPRESS24', name: "JABA COCA COLA EXPRESS 250ML x 24 unidades", price: 10104, category: "RETORNABLE", image: "catalogo/JABA_COCA_COLA_EXPRESS_250ML_x_24_unidades.jpg", flavors: ["COCA COLA ORIGINAL", "COCA COLA ZERO", "FANTA", "SPRITE"], flavorIds: { "COCA COLA ORIGINAL": "EXPRESS24-01", "COCA COLA ZERO": "EXPRESS24-02", "FANTA": "EXPRESS24-03", "SPRITE": "EXPRESS24-04" } },
  { id: 'POWA850-01', name: "POWERADE 850ML x 6 unidades - AZUL", price: 5850, category: "BEBIDAS", image: "catalogo/POWERADE_850ML_x_6_unidades_-_AZUL.jpg" },
  { id: 'POWA850-02', name: "POWERADE 850ML x 6 unidades - ROJO", price: 5850, category: "BEBIDAS", image: "catalogo/POWERADE_850ML_x_6_unidades_-_ROJO.webp" },
  { id: 'MINI250-01', name: "COCA COLA MINI 250ML x 6 unidades - COCA COLA", price: 6200, category: "BEBIDAS", image: "catalogo/COCA_COLA_LATA_350_ML_x_6_unidades_-_COCA_COLA.webp" },
  { id: 'MINI250-02', name: "COCA COLA MINI 250ML x 6 unidades - COCA COLA ZERO", price: 6200, category: "BEBIDAS", image: "catalogo/COCA_COLA_3LT_DESECHABLE_x_6_unidades_-_COCA_COLA_ZERO.webp" },
  { id: 'MINI250-03', name: "COCA COLA MINI 250ML x 6 unidades - FANTA", price: 6200, category: "BEBIDAS", image: "catalogo/COCA_COLA_LATA_350_ML_x_6_unidades_-_FANTA.jpg" },
  { id: 'MINI250-04', name: "COCA COLA MINI 250ML x 6 unidades - SPRITE", price: 6200, category: "BEBIDAS", image: "catalogo/COCA_COLA_LATA_350_ML_x_6_unidades_-_SPRITE.jpg" }
];
